..............................................................ooooooooooo...........................
.##########.#####..##.##.##...#.#####..#.#.#.##.######..####.#o#########o#########..##########.##.#.
.............................................................ooooooooooooooooooo....................
.#####.###.##.#.########.#.###.##################..##.######.o#####oo##########o###..#####.######.#.
...............................................oooooooooooooooooooooooooooooooooo...................
.#.#.#.###################..###################o###############o########o#######o#######.####.#..#..
..............................................oooooooo......oooooooooooooo....oooo..................
.##.######.#########.##..#..#.###########.####o######o.#####o#########o##o#.##o##o###..###..####..#.
.........................................ooooooooooooooooooooooooooooooooo....ooooo.................
.#####.#.########..####.#################o#################o#####o#######o.###o###o#.##############.
....................................ooooooooooo.........ooooooooooooooooooooooooooooooo.............
.##..##.###.#############..#########o#########o########.o###o#######o######oo##oo#####o##...##.#.##.
...........................ooooooooooo.....ooooo..ooooooooooooooooooooooooooooooooo..oooooooo.......
.############.##.#..#######o#########o..###o###o##o#######o####o##################o##o######o###.##.
..................ooooooooooo........o.oooooooooooooooooooo.oooooooooooooo......ooooooooooooooooooo.
.#.##############.o#########o##.#.###o#o##################o#o############o######o##o######o#######o.
...........ooooooooooo.....ooooooooooooo.......ooooooooooooooooooo....oooooooooooooo....oooooooooooo
.########..o#########o###.#o####o######o#######o#################o####o#######o####o####o##########o
......oooooooooooooooooooooooooooooooooo.......o.............ooooooooooooooooooooooooooooo.........o
.#.#..o#########o###########o##########o.######o###.#########o###############o######o####o#.######.o
.....ooooooooooooo.........ooooooooooo.o..ooooooooooooooo....o.......oooooooooooooooooooooo........o
..###o######o####o####.####o#########o#o##o#############o####o#####.#o####################o########o
....oooooooooooooo.ooooooooooooooooooooooooooo........oooooooooooooooooooooooooooooooooooooooooooooo
.###o####o#######o.o##################o#o####o.###..##o############o####################o##########o
.ooooo..oooo...oooooooooo.........ooooooo....ooooooooooo...........o..............oooooooo.........o
.o###o.#o##o##.o########o######.##o#####o##.#oo########o.####.#####o############.#o######o##.#.####o
oooooo..oooooooooo.....ooooooooooooooooooooooooooo.....o..........ooo......ooooooooooooooooo.......o
o####o##o########o##.##o#oo############o##o######o##.##o###.######o#o##.#..o########o######o#######o
o....oooooooooooooooooooooooooooooooooooooooooooooooooooooooo....ooooooooooooooo...oooooooooooooo..o
o####oo##############################oo#####################o####o#############o##.o######o#####o.#o
o.ooooooooooooo......................ooo..................ooooooooo.........ooooo.ooooo...o.....o..o
o#o###########o##.#####.##.##.#######o#o########.######.##o####o##o#########o###o#o###o###o#####o##o
oooooooooooooooooooooo......oooooooooooooooooooooooooooooooo...o..o......ooooooooooooooooooooooooooo
o#########o##########o#.#.#.o##############################o...o##o###.#.o##########o##o###########o
o..ooooooooooooo.oooooooo..oooooooooooooooo.........ooooooooooooooooooooooooo.......o.oooooooooo...o
o##o###########o.o######o##o##############o.#######.o#################o#####o#######o.o########o###o
oooooo........oooooooooooooo..........oooooo........o.............oooooooooooo.....oooooooooooooo..o
o####o#####...o########o##oo##.#####.#o####o########o#####...#.#.#o#######o##o#####o############o##o
o.oooooo...oooooo...oooooooooooooooooooo..ooooooooooooooo.oooooooooo......o..o....oooo.......ooooooo
o#o####o###o####o#..o#######o##########o.#o########o####o#o########o#####.o##o#.##o##o.##.###o#####o
o.o....o..oooooooooooooooooooooooooooooooooooooooooooooooooooo.....oooooooooooooooooooooo.oooooooooo
o#o###.o##o####o######################o#o###o########o#######o#.###oo#########oo########o#o########o
oooooooooooooooooooo.............oooooooooo.ooooooooooo.oooooooooo.ooooooooooooooooo....oooooooooooo
o##################o.###..#####..o########o#o#########o.o########o.o#oo############o.##.o##########o
o.........ooooooooooo.oooooooooooooooo..ooooo.........o.o...ooooooooooooo....ooooooooooooooooo.....o
o###.###..o#########o#o##############o##o###o.##.#####o#o#.#o###########o####o########o######o#####o
o....oooooooo....oooooo.........ooooooooooooooooooooooooooooooooo.......ooooooooo.....o.....ooo....o
o#.##o######o#.#.o####o.#.######o##########o#############o######o#####.#oo######o##.#.o###..o#o###.o
o....o.oooooooooooo.oooooo......o.........ooo............o..oooooooooooooo..ooooooooooooooooooo....o
o####o#o##########o#o####o###..#o####.####o#o#######.##.#o.#o#######o####o#.o########o##o#####o##.#o
o....ooooooooooooooooo..ooo.....o....oooooooooooooo......o.ooo......o...oooooooooo.ooooooo...oooo..o
o####o######o########o##o#o#.###o####o############o######o#o#o.##..#o###o########o.o##o##o##.o##o##o
oooooooooooooooooooooooooooooooooooooo......ooooooooo..ooooooooooooooooooooooooooooooooooo.ooooooo.o
oo#########o############oo###########o######o#######o.#o###o########oo####o##############o#o#####o#o
oo........oooooooo..oooooo.........ooooooooooooooooooooooooooo......oooooooooo...........o.o....oooo
oo###.###.o######o.#o####o######.##o#############o###o###o###o##.##.o##o#####o##.########o#o####o##o
oooooooooooooo..ooooooooooooooo...ooo.........ooooooooooooooooooooooooooooooooo..........ooooooooo.o
o############o#.o##o##########o#.#o#o.########o####oo######o##o#######o#oo####o######.#.#o#######o#o
o.....ooooooooooooooooooooo...oooooooooooooooooo.ooooooo..ooooo.......oooooooooooo.oooooooo.....oooo
o#####o###################o###o################o.o#####o##o##oo##.####oo####o####o#o######o####.o##o
oooooooo................oooooooo...............ooooo...oooooooooooooooooooo.ooooooooo....ooooooooooo
o######o.##########.####o######o..#############o###o#.#oo####o####o#######o#o#######o.##.o#########o
o......o.......oooooooooooo.ooooooooooooooooooooooooooooooooooooooooo.oooooooo..oooooooooooooooooooo
o#.####o#######o##########o.o###oo###############################o##o.o####o#o.#o####o#############o
oooooooooo.....oooooooooooooooooooooooooo.......................ooooooooooooooooooooooo............o
o########o#...#o############o###########o###.####.########.###..o#####o###############o.######.#.##o
o..oooooooooooooo...........o.....ooooooooooo..................ooooooooooo.........ooooo...........o
o..o########oo##o.##########o#####o#########o##.#######.#.###.#o#########o.########o###o###########o
ooooooooooooooooo..........oooooooooo.oooooooo.........oooooooooooo....oooo.......ooooooooo........o
o###############o######.#.#o########o#o######o####.##.#o##########o####o##o#.#####o#######o#.######o
o..............oooooooooooooooo.....oooo.oooooooooooooooooo.......o....o..o....oooooooooooooo......o
o##.#######.###o####o#########o###.#o##o#o#########o######o#######o####o##o#.##o############o###.##o
o............oooooooooooooooooooooooooooooooooooooooooooooooo.oooooo..oooooooooooooooooooooooooooo.o
o########.#.#o#####o#########o###o###o##############o#######o#o####o.#o####o####oo###############o#o
ooooooooooooooo...oooooo....ooo.oooooo.............oooooooooooooooooo.o.ooooo.oooooooo.....ooooooooo
o#############o.#.o####o####o#o#o###oo###.####.####o#####o#######o##o#o#o###o#o######o####.o#######o
o.............o...ooooooooo.oooooooooo............ooooooooooooooooooooo.o...o.o.....ooooooooo......o
o..##..#####..o#.#o#######o.o######ooo.#####.###.#o##o############o###o.o.##o#o###..o#####o#o######o
o..........ooooooooo..ooooooooooo.oooooooo..oooooooo.o.........oooooooooooooooo.....o....oooo......o
o###.######o###o###o.#o####o####o#o######o##o######o#o..####.##o#####o########o##.##o####o#oo######o
o.........ooooooooooooooooooooooooooooooooooooooooooooooooooo..o....ooooooooooooooooooooooooooo....o
o.###.####o######oo#oo###o####o##o######o##########o########o##o####o######o##################o####o
o.......ooooooooooooooooooooooooooooo.ooooooooooooooo......ooooooooooooooooooooooo.......ooooooooooo
o.######o###o########o####o#########o#o########o####o..###.o##o###########o######o#.#####o#########o
o.......o..oooooooooooo...o.......ooooo........o....o..oooooooooooo...oooooo..oooooooo...o.........o
o#######o##o######o###o##.o.######o###o#.#.####o####o##o##########o###o####o..o######o##.o#########o
o......ooooooooooooooooo..o.......oooooo......oooooooooooooooooooooo..ooooooooo......ooooooooooooooo
o######o#o######oo##o##o.#o###.##.o####o####..o####################o..o######oo###.##o#############o
o.....ooooooooooooooooooooooooo...o..ooooooooooo..................oooooooooooooooooooooo...........o
o#.###o###o###################o##.o##o##oo#####o#####.#.##########o##oo###########o####o#######.###o
o....oooooooooooooo...........o...ooooooooooooooooo..............ooooooooooo......oooooooo.........o
o###.o############o#.#########o###o###o###########o.##.#.####.###o###o#####o####.#o######o..##.####o
o....o.......ooooooooo....oooooooooooooooooooooooooooooooooooooooooooo....ooooo.ooooo..oooo........o
o####o.###.#.o#######o####o##################o##################o####o###.o###o#o###o##o##o########o
o....ooooooooooooo...oooooooooooo.........ooooooooooooooooooooooooooooooooooooooooooooooooooooo....o
o####o###########o###o##########o#########o#####o####################o########################o####o
o..oooooooooooooooooooooo......ooo...oooooooooooooooo..........ooooooooo....................ooooo..o
o##o############oo######o#####.o#o###o##############o##.#.###.#o#######o#########.#####.####o###o#.o
ooooooooooooooooooooooooooooooooooooooooooo.........o........oooooooooooooooooooooooooo...oooooooooo
oo####o###########o########o##############o##.######o##.###.#o###o####################o.##o########o
oo...oooo........oooo......o.........oooooooooooooooooooooooooooooooo.................o..oooooooo..o
oo..#o##o########o##o###.##o##.#.####o###########oo####oo#####o#####o##.####..#######.o##o######o##o
ooooooooooooooooooooooo..oooo.....ooooooo.......oooooooooooo..o....ooooo............oooooooooooooooo
o#####################o##o##o#####o#####o#######o#####oo###o##o#.##o###o##.#.#.#.##.o##############o
o............oooooooooooooooooooooooooooooooooooooo...oooooooooooooooooooo.....ooooooooooo.........o
o####.###.#..o#################o######oo###oo#####o###oo######o#######o##o##.##o#########o#####.###o
o...........oooooooooo.....ooooooo..ooooooooooooooooooooooooooooooooooooooo.ooooo........o.........o
o#.#.###..##o########o#####o#####o#.o############o#####o########oo########o#o###o########o#..####.#o
o.........oooooooooooooooooo...ooooooo......oooooooooooo....oooooo..oooooooooooooooo.....o.........o
o#######.#o##oo############o.##o#####o#.##.#o#########oo####o####o##o########o#####o###.#o##.####.#o
o.......oooooooooo.........ooooooooooooooooooooooooooooooooooooooo.oooooooooooooooooo..ooooo.......o
o#.#####o##o#####o####.####o#########oo#############o###oo######oo#o#oo#############o.#o###o##.###.o
o...oooooooo.....o......ooooo..oooooooo...........oooooooooooooooooooooo...........ooooooooooooooooo
o.##o######o.##.#o######o###o##o######o###.###.#.#o###############oo###o######...##o####o#########oo
o...ooooooooooo..o.....oooooooooooooooooo.......oooooooooo......ooooooooooo........ooooooooo....oooo
o###oo########o#.o#####o#o##############o#######o########o.#..##o####o####o###.####o#######o.###o##o
oooooooooooooooooooooooooo..........ooooooooooooooooooooooooooooooooooooooooooooooooo.....oooooooooo
o#########o########o#####o####.#.###o########oo###############o#####################o##.##o#######oo
o.......oooooooooooooooooooooooo....o......oooooooooooooooooooo.............ooooooooooo.oooo.....ooo
o.##.###o########oo##o#########o####o##.###o##################o##.####.##...o#########o#o##o#####o#o
o.....ooooooooooooooooooooooooooo...oooooooooo............ooooooooo....ooooooooooooooooooooooooooooo
o..##.o#########o#######oo######o###o########o.#.###..####o#######o####o#####o##########o####o#####o
o.....o.........o.......oo......o...o........o............o.......o....o.....o..........o....o.....o
