..............................o.................................................................
.###..##.###.#.####.##..######o############..######.#########..##.####.##.#####.##.###.########.
........................oooooooooooo............................................................
.#...#####.##.##..#.#.##o##########o##.#######.####..####.#.############.#####.#.##############.
..................oooooooo........ooooo.........................................................
.#.###.###########o######o####.###o###o###.##.######.########..#########.#################..###.
...............ooooooooooo........o.ooooooooooooo...............................................
.###..###..####o########oo##.#####o#o###########o.##############.##.#.####.###.###..#.##.#.####.
...............o.......ooooooooo.ooooooooooooooooooo............................................
.######.#######o#######o#######o#o##o##############o####.#...##.#.########.#.##.##.############.
............oooooooooooooooooooooooooo............ooooo.........................................
.####.######o#######o################o####.#..##.#o###o########.######.##.##.#######.##...####..
........ooooooooooooooooo.......oooooooooooooooooooo.ooooooooooooo..............................
.######.o##########o####o#####..o##################o#o###########o#.###.##.####.###############.
.......oooo.......oooooooooooooooooooo............oooo........ooooooo...........................
..##..#o##o###.##.o###o########o#####o#######.#.##o##o####.#.#o#####o#######.##########.###.###.
.....oooo.o....oooooooooooooooooooooooooooooooooooooooooooooooooooooo...........................
..###o##o#o.###o################o#########################o#########o#.######.##.#########..###.
...oooooooooooooooooooo.........o......ooooooooooooooooooooooo...ooooooo........................
.#.o####oo###oo#######o##.######o#.####o#####################o..#o#####o###.#######..###.######.
ooooooooooo.ooo......ooo....ooooooooooooo........ooooooooooooooooooooooooo......................
o#########o#o#o######o#o####o###########o########o############o##########o######...###..#####.#.
o.......ooooooooo....oooooooooo....oooooooooooooooooooooooooo.o......ooooooooooo................
o..#.##.o#######o..##o########o.##.o##########oo############o#o#.####o#########o#.#.###########.
ooooooooooooooooooooooooooo.oooooooooooooooooooo...ooooooooooooooooooo.ooooooooooo..............
o############oo#####o#####o#o##################o###o#################o#o#########o#.#######.###.
o............ooo....o..oooooooooo......ooooooooooo.o.................ooooooo...ooooo............
o.###########o#o####o#.o########o######o#########o#o##.####.#########o#####o##.o###o..#.##.##.#.
o......oooooooooooooooooo......oooo.ooooooooooooooooooooooo.........oooooooooooooooooooooooooooo
o##.###o#########oo##o##o#.####o##o.o#######o#############o##..#####o#o#########oo#############o
o....ooooooooooooooooooooooooooooooooooooooooooo..........o...ooooooooo....oooooooo............o
o.###o#####o########o#######o####o###o#########o###.#.#.#.o###o######oo..#.o######o###..#.##.##o
o...ooooooooooooooooooooooooo..oooooooo........o.....oooooooooo......ooooooooooooooo...........o
o###o#######################o.#o######o####.###o#####o########o######o######o######o###########o
ooooooooo.........ooooooooooooooo...oooooo..oooooooooooo....ooooooo.ooooo..ooooooooooo.........o
o#######o#########o##########o##o.##o####o##o######o###o####o#####o#o###o##o#########o.###..###o
ooooooooooo......oooooooooooooooooo.o..ooooooooooooooooooooooooooooooooooooooooooooooooo.......o
o#########o###..#o##o#########o###o#o..o#####o##########o#######o####o###########o#####o#####.#o
o.....ooooooooooooooooooooooooooooooooooooooooooo.oooooooooooooooooooooooooooo.ooooooooooooooooo
o###.#o#######o##############oo#################o#o##########o###############o#o##o############o
o....oooo.....o............oooooo..............oooooooooooooooooooo..........oooooooo..........o
o####o##o###.#o###.#######.o####o#########.####o##o###############o##########o######o#.#.####.#o
o....o.oooooooooo..........o.oooooo...........oooooooooo....oooooooooooooooooooooooooooo.......o
o####o.o###o####o####.####.o#o####o######.####o##o#####o#.##o##########oo##############o##.#.##o
ooooooooooooooooooooooooooooooooooooooo.oooooooooooooooo...ooooooooooooooooooooo.ooooooooooooooo
o###########oo###oo###################o.o##############o###o##o################o#o#############o
o...oooooooooooooooo................oooooooooo.....ooooooooooooo.........oooooooooo............o
o..#o##########o###o#######.########o########o##.#.o########o##o######...o########o###.#..#####o
ooooooooooooooooooooo..............ooooo.ooooooooooooooooooooooooooo.....o...ooooooooooo.......o
oo########o#####o###o.##.####.#####o###o#o#################o##o####o#####o###o#########o#..###.o
oooooooo..o...oooooooooooooooooooooooooooo......ooooooooooooooooooooo..ooooooooo....oooooooooooo
o######o##o##.o##o########o##############o######o###################o##o###o###o####o##########o
o..oooooooooooooooooo.....o..............o.oooooooooooooooooooooooooooooooooooooo..ooooo.......o
o##o################o#.##.o.#.#.####.#.#.o#o################o###################o##o###o#######o
o..o..............oooooo.oooo.......oooooooooo..........ooooooooooooooooo.......o.oooooooooooooo
o##o.#######.##.##o####o#o##o######.o#####o##o.#######.#o###############o#.#....o#o###o########o
ooooooo........ooooooooooooooooooooooooooooooooooo......o...........ooooooo.....ooooooooooo....o
o#####o########o###########ooo###########o#######o##.###o###.#######o#####o##.#.oo########o####o
o....oooooooooooooooooo....ooo...........o......ooooooooo..........ooooooooo...oooooo...oooo...o
o###.o##o#############o..##o#o#.####.##.#o.#####o#######o###.#...##o#o#####o###o####o###o##o###o
o.ooooooo.............o....oooooooooooooooo...ooooooooooooooo......ooooo..ooooooooooooooooooo..o
o#o#####o##.###.#.#.#.o####oo##########o##o#.#o#############o#..###o###o.#o#######oo###o####o.#o
ooooooooooooooooo.ooooooooooooooo...ooooooo...o.............oooooooooo.o.oooooooooooooooooo.o..o
oo##############o.o####o########o#.#o#####o#.#o##.######.#.#o########o.o#o###o######o#####o#o#.o
ooooooooo.....ooooooooooooooooooooooooo.oooooooo.....oooooooooooooooooooooooooo.....oooooooooo.o
o#######o.####o##ooo#########o########o.o####o#o#####o##########o#####o###o###o#####oo#######o#o
o.....ooooo...o.ooooo........o......oooooooooooo.....o......oooooo.ooooooooooooooooooooooooooooo
o###.#o###o#.#o.o###o.####.##o####.#o###o######o##.##o######o####o#o#####o#o###########o#######o
o....oooooooooooooooooo......oooooooooooooooooooo....o.....oooooooooooooooooo.........ooooo....o
o####o##o#############o#.####o#########oo#######o####o###.#o####oo####o###o#o#.#..##.#o###o.###o
oooooooooooooooo...ooooooooooooooo...oooooooooooooooooo..oooooooooooooooooooooooooooooooooooo..o
o##############o###o#############o###o###o############o##o#####oo##########o######o#########o.#o
o..............ooooooooooooooooooooooooooooooooo..ooooooooooooooo..........o......o.......oooooo
o#.##.#########oo############o####oo###########o.#o#####oo######o####.##.##o#..###o#######o####o
o...........ooooo..........oooooooooo......oooooooooooooooooo.oooooo.....oooo....ooooooooooooooo
o###.#.#####o###o######..##o########o..####o#######o########o#o####o###.#o##o#...o#############o
o........ooooooooooooooooooooooo....oooooooooooooooo........o.ooooooooooooooooooooo............o
o####.#.#o######o##############o###.o##############o.#######o#o#############o#####o#.#######.#.o
o.......ooooooooooooooo.ooooooooooooooooooooooooooooo..ooooooooooooo.....oooooooooooooooooo....o
o####.##o#############o#o###########o###############o#.o#####o#####o###.#o######o#########o###.o
o......oooooooooooooooooooooooooo.ooooooooooooooooooooooo...oooooooooooooooooooooooo..oooooooooo
o######o######o#################o#o##############o####o#o###o###############o######o##o########o
ooooooooooooooooooooooo..ooooooooooooo......oooooooooooooooooooooooooooooooooooooooooooo.......o
o#####################o.#o###########o######o#######o###########o###################oo#o.######o
o........ooooooooooooooooooooooooooooooooooooooooooooo....oooooooo...............ooooooooooo...o
o########o##################o#########o############o#o####o######o###########.###o####o####o##.o
oooooooooooo................o.......oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o##########o.##.##.####.####o.######o#######o###########oo#oo#################o#####o##########o
o.......ooooooooooooooooooooooooooooo......ooo...ooooooooooooo............oooooooooooooooooo...o
o..##.##o###############o###########o..##.#o#o###o#######o###o####.#######o#####o##########o###o
o.......o...............o..ooooooooooooooooooooooooo....oooooo..........ooooooooooooooooooooo..o
o.#.####o###.#.##.#####.o##o###############o#######o###.o####o#######.##o##########o########o.#o
o....oooooo............ooooo.......oooooooooooo...oooooooo...o.......ooooooo...oooooooooooooo..o
o##.#o####o######.#####o##oo###.###o##########o###o####o#o###o#...###o#####o###o############o.#o
o...oooooooooo.........ooooo....oooooooooooooooooooooo.ooooooooo.oooooooooooooooooooo..ooooooo.o
o.#.o###o####o#########oo##o####o##########o#########o#o##o####o#o##################o#.o#####o#o
ooooooooooooooooooooooooooooooooo.........ooooo......ooooooooooooooooo..............oooooooooooo
o##############o##########o#####o#######.#o###o.#####oo###o##########o######.###..#.o#####oo###o
o..............oooooooooooooooooooo...ooooooooooooooooooooooo........o...........ooooooooooo...o
o####..#.######o###############o##o###o######o#o#######o####o.####.##o###.#####.#o#########o###o
o............oooo.............ooooooooooooooooooo......ooooooo.....ooooooooooooooo........oooooo
o######..####o##o#############o##o###o##########o##...#oo####o###.#o#############o##.#.###o####o
o............o.oooooooo...ooooooooooooooo.......oooooooooo.oooooo.oooooooooo.....o.......ooo...o
o######.###.#o#o######o###o#############o..#####o########o.o####o#o########o.####o#######o#o###o
o......oooooooooooooooooo.o.............o......ooo......ooooooooo.o........o.....o.......o.o...o
o..####o#########o######o#o#..##.#.##.#.o##.#..o#o##.###o#######o#o.#.##.##o.#.##o######.o#o#..o
o.....ooooooooooooooooooooooooo........oooooooooooooooooo......ooooooooooooo....oooo...ooooooo.o
o.#.##o#########o######oo#####o######.#o################o.#####o###########o####o##o#.#o#####o.o
o..ooooooo.....ooooooooooooo..o........o........ooooooooooo..ooooooo.....ooooooooooooooooo...o.o
o#.o#####o#####o######o####o##o.###..#.o##.#####o#########o##o#####o#####o#####o#########o.#.o#o
o.oooooooooooooooo...oooooooooooo......o........o....oooooooooooooooooo..o...ooooooooooooooooo.o
o#o##############o#..o#######o##o######o###.##.#o.###o######o####o####o.#o###o#####oo########o#o
oooooo.........ooooooo.......oooooooooooooooooooooooooo.....o..ooooooooooooooooooooooooooooooooo
o####o.#####..#o#####o#..####oo###o###########o#######o##...o##o###########oo##o###############o
o..ooooooooooooooooooooooo..ooooooooo.........oooooooooooooooooo...........ooooooo.............o
o.#o##########o#####o####o##o#######o.##.##.##o#########o######o####.####.#o#o###o#.########..#o
ooooo.......oooooooooooooooooooo....o.......oooo....ooooooooooooo..........ooooo.o.............o
oo##o.######o###########o######o####o#.##..#o##o####o####o######o.####.###.o###o#o###########.#o
oo..o.......o...........o......o....o.......o..o....o....o......o..........o...o.o.............o
