...................................................................................................ooooooooooooooooooooooooooooooooo................................
.########.################.##.###############.############.###########################.#..#####.###o###############################o##.##.###.#################.###.
...................................................................................................o...........................ooooooooo............................
.########.#..#####.##.#######.####..##..##.##########.##.#########.#####.########.#########.####.##o##.#####.##..########..###.o#######o.###.#####.###########.####.
...............................................................................................oooooooooooo...........oooooooooooooooooo............................
.#####.#.##########.##.##.#######.###.##.###.######################.###.#######.######.#..#####o##########o###########o################o#.#.###.#.#################.
..............................................................................................oooooooooooooo.........oooooooooooo..oooooo...........................
.##############.###.##################.#######.##..###########.######.##########..#########...o####o#######o#######.#o##########o##o####o.###.###############.##.##.
.........................................................................................ooooooooooooooooooooooo..ooooooooo.....o..ooooooooooooooooooooooooo........
.##.#.##########.########.#####.#####.###########.##################################.##.#o#######o#############o##o#######o#####o##o#######################o##.###..
....................................................................................ooooooooooooooooooooooooooooooooooo.ooooooooooooo..................ooooooooooooo
.#.####.######.#.#######.#######.##.##.###.########.############.###########..######o######################oo####o####o#o##o########o..###########.####o###########o
....................................................................................o...................ooooooooooooooooooooooooooooooooooooooo......ooooooooooooooo
.###.######.##..####.#####.##.#..############.##########.##.#.#.####################o################.##o#######o#######o#####################o###.##o#############o
.............................................................................ooooooooooooooooooooo..oooooo......o.ooooooooooo.................oooooooooooooooooooooo
.#.#.##########.################..#.#.#####.#.#.######.##.##.####.#.##.##.###o###################o##o####o######o#o#########o#############.###o####################o
.............................................................................o.................oooooooooooo.ooooooo.....oooooo...............oooooo................o
.########################################.#.#######.#.#######################o#####.###########o#######o##o#o#####o###.#o####o###.##.###.#.##o####o###..####.######o
.....................................................................oooooooooooooo............ooooooooooooooooooooooooooo...o...............ooooooooooooooooooooo.o
.########.####################.###.#####.###########.###.############o############o.#.########.oo############o#####o#####o###o.#########.####o###################o.o
...............................................................ooooooooooooo.oooooooo.........ooooo..........o..oooooooooooooooooooooooooooooo.................ooooo
.#########.#####..##########.#####.######.######.#####.########o###########o#o######o######.#.o###o####..####o##o###o#####o##################o##.####.####.####o##oo
.............................................................oooo.......oooooooooooooooooo....oooooooo...oooooooooooooooooooooooooooooooooooooooooo...........oooooo
.###.###.###.#########.#################.#.###.#######.##.###o##o.######o#######o########o####o######o###o####o#########o######o##################o#######.##.o####o
.............................................................oooooo....ooooooooooooo.....o....o....ooooooooooooooooooooooooooooooooo..............o.oooooooooooooooo
.#.##.#####..##########.############.########.#####.##.######o####o####o###########o...##o####o.#.#o#####oo######o#######o#########o#####.####.###o#o##############o
.............................................................ooooooooooooo.........o...oooooooooooooooooooooooooooooooooooooo..ooooooooooooo..oooooooo.............o
.#..###.#######..####.#############.#.###..#.###########.####oo##########o########.o###o##########o#######oo##########o#####o##o###########o##o######o.#########.##o
......................................................oooooooooo......oooooooooooooooooooooooooooooooooooooo.......ooooooooooooooooooooooooooooooooooooooooooo.....o
.#...##.####.################################..######.o########o##.###o########o###########################o#######o###o##################o##o####o##########o#####o
..................................................ooooooooo...oooooooooooooooooooooooooooo......oooooooooooooooooooooooooooooo...ooooooooooooooooooooooooooooooooooo
.###..##.######.#..###.##.####.#.#####.#..#######.o#######o.##o##########################o######o###################oo#######o###o##############o#################oo
.................................ooooooooooooooooooooo..ooooooooooooooooooo...oooooooooooooooooooooo..............oooooooooooooooooooooooooooooooooooooooooooooooooo
.#.###############.###.##.#######o###################o#.o###o#############o###o####################o####.#########o################o###############################o
...........................ooooooooooooooooooooooooooooooooooo...........ooooooo.................oooooooooo....oooooooooo....ooooooooooo...........................o
.######.########.######.##.o##########o####################o#o#####.#####o#####o.################o########o####o########o###.o#########o###.#.#######.#####.##.#.##o
..................oooooooooooooooooooooooo...oooooooooooooooooooooooooooooooooooooooooooo........o..ooooooooooooooooo...o..ooooooooooooooo.........................o
.##.###########.##o#################o####o###o####################o#####################o#.######o.#o###############o#.#o##o#############o#####################..##o
................oooooooooo.........ooooooooooooo...........ooooooooooooooo..............o........ooooooooooooooooooooooooooooooooo...oooooooooooooooooooooooooooo..o
..##..#######.##o########o###.###.#o###########o###########o#############o##..####.#####o########o########o###########o##########o###o##########################o##o
..............oooooooooooooo......oooooooooooooooooooooooooooooooooooooooooooo.......oooooo..ooooooooooooooooooooooooooooo....ooooooooooooooo...................o..o
.###.###.###.#o#####o######o###.##o###########o##########o########oo#########o###.###o####o.#o#####o########o############o####o#############o#.########.########o##o
........oooooooooo..o....ooooooooooooooooooooooooooooooooooo....oooo.....ooooooooooooooo.ooooooooooo.......oooooo..oooooooooooooooooooooo..ooooooo...........ooooooo
.###.###o########o##o##.#o########o###############o########o####o##o#####o####o########o#o#########o.##.###o####o##o########o###########o##o#####o###########o#####o
ooooooooooooo.ooooooooooooo....oooooo..........ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....ooooooooooo.o.........oooooooooooooooo...ooooooooooo
o###########o.o###########o##.#o####o#########.o################o#####o######o########o###########o########o####o#########o#o#####.###o#####o########o##.o#########o
o...........ooooooooooooooooooooooo.o..oooooooooooo.............ooooooooooooooooo.oooooooooooooooooooooooooooooooooooooooooooooooooooooo.ooooooooooo.oooooooo......o
o######.####o###############o#####o#o##o##########o#######.####.o#######o#######o#o###########o####o########o#######o######oo##########o.o#########o.o######o######o
o...........o.......oooooooooooooooooooooooooooooooooo..........oooooooooooooooooooooo.oooooooooooooooo...oooooooooooooooooooooooooooooooooo.....oooooo.....o......o
o##########.o#.#####o###########o########o###########o##.##.####o###########o########o#o##############o###o###o##########o###########o##o##o#####o####o#####o######o
o...........o....oooooooooooooooooooooooooooo...ooooooooooooooooooooooooooooooooo.ooooooooooooooooooooooooooooo.....oooooooooooooooooooooooo.....ooooooooooooooo...o
o###.#.####.o####o##################o#######o...o######o##################o#####o#o###########o#########oo####o#####o#####o################o#####oo############o###o
o...........oooooooo.oooooooooooooooooooo.ooooooooooooooooo.............ooooo..oooooooooooooooooo....oooooooooooo...o.oooooooooooooooooooooooooooooooooooooooooooooo
o.###.#..###o######o.o##################o#o##########o####o#.#.#########o###o##o#ooo############o#.##o##########o.##o#o##################oo#####o###o##############o
o..........ooo....oooooooooooooooooooooooooooo.......o..oooooooooooooooooooooooooooooo....oooooooooooooo..oooooooooooooooooooooooooooooooooo...oooooooo............o
o##.#.#####o#o.#..o#o########################o##...##o##o##############o#o###########o####o############o##o######o#########################o..#o######o############o
o...oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.........ooooooooooo...................oooooooooooooooooooo..........o
o###o#######o######o#############################o###################o##o########o#######o###o#########o#########o#####.##.##########o#######o##########o.#########o
ooooooooooooooooooooooooooo......................oooooooooooooooooooooooo........ooooooooooooooooooooooooooooooooooooooooooooooooooooo.....oooooooooooooo..........o
o########o###o############o####.#################o######################o########o###################################################o#####o###########oo###..#####o
o.......ooooooooo........ooo................oooooooooooooo.ooooooooooooooooooooooo.................................ooooooooooooooooooooooo.o.........ooooooooooooooo
o#######o###o###o########o#o##########.#####o############o.o#####################o.###.############..######.#######o#####################o#o######.#.o#############o
o......ooo..ooooooooooooooooo......ooooooooooooooo....ooooooo..............oooooooooo................oooooooooooooooooooo...........ooooooooo.......oooooo.........o
o######o#o##oo###o##########o######o#############o####o#####o#######...####o########o################o##################o####.######o#######o###.###o####o##..#####o
oooooooooooooooooooo....oooooooooooooooooooooooooooooooooooooooooooooooo...ooooooooooooooooo....ooooooooooooooooooooooooooooooooooooooooooooooooooooooo..o.........o
o##########o#######o###.o#########o##########oo########################o.##o###############o####o#####o###########################oo##o######o########o##o#########o
o........oooooooooooooooooooo.....o.....ooooooo.......................ooooooooooooooooooooooooooo....oooooooooooo..........oooooooooooo......ooooooooooooooooooooooo
o########o######o###########o#####o#####o#####o###########..##########o####o####################o####o##########o######..##o##########o####.#o##########o#########oo
o.oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..............ooooooooooooo....ooooooo....ooooooo....ooooooooooooooooooooooooooooooooo
o#o#######o#################o###########################o###############o####o##.########.##o###########o##.#o#####o.###o#####o####o######o#######o################o
oooooo....o.............oooooooooooooo................ooooo....ooooooooooooooooo......ooooooooooooo...oooooooooooooooooooo....ooooooo..ooooooooooooooooooooooooooooo
o####o####o#####.#####.#o############o####..####.#####o###o##.#o###############o###.##o###########o.##o#####o############o.###oo####o##o#########o#################o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....oooooooooo....o...........oooooooooooooooooooooooooooooooooooooooooooooooooooooooo.........o
o#############o############o##########o############################o##.#o########o####o#########..oo####oo####################o###o###o##################o#####.###o
o....ooooooooooooooooo....ooooooooooooooooo..................oooooooooooo........o.ooooooooooooooooooooooo...........oooooooooooooooooooooooooo........oooooooo....o
o.###o###############o###.o###############o##########.####.##o##########o########o#o####################oo.#.########o##########o#############o..##.##.o######o####o
ooooooooooooooooooooooooooo............ooooooo...........ooooooooo.ooooooooooooooooo....................oooooooooooooooooo.ooooooooo......oooooooooooooooooooooooooo
o############oo###########o#######.###.o#####o##.#####.#.o#######o#o###############o########.###########o#######o########o#o#######o###..#o#########oo#############o
o...ooooooooooooooo......ooo...........ooooooooo........oooooooooooooo.......ooooooooooooooo............o......oooooooooooooooooooooo....oooo.ooooooooo............o
o.##o#############o######o#o###########o#######o#######.o######oo#o##o######.o#############o#.#...#..###o.###.#o#######o############o####o##o#o#######o#####.##.###o
oooooooooooooooooooooooooooooooooooooooooooooooo......oooooooooooooooooooooooooooooooooooooooooo...ooooooooooooo...ooooooo........ooooooooooooo....ooooo...........o
o###############o#######o#o#o##################o######o###o#############o########o#############o##.o###########o###o#####o##.#####o#####oo####o####o###o#.#######.#o
o..........ooooooooooooooooooooooooooooooo...oooooooooooooooo......oooooooooooooooooooooo.....ooooooooooooooooooooooo....ooooooooooooooooooooooo...o.ooooooo.......o
o##########o############o################o..#o#####o########o######o#####o##############o###.#o###########o#########o####o##########o########o#o###o#o#####o#######o
ooooooooooooooooo..ooooooooooo..........ooooooooooooooooooooooooooooooooooo..oooooooooooooooooooo....oooooooo....oooooo..o..........o....oooooooooooooooooooooo....o
oo##############o##o#########o########.#o##oo##o##################o#####o#o##o##################o####o######o####o####o#.o.####.####o##.#o####################o.###o
oooooooo.....oooooooo......ooooooooooooooooooooooo......ooooooooooooooooooooooo................ooooooooooooooo..oooooooooooooooo.ooooooooooooooooooooooooooooooooooo
o######o####.o######o####.#o##o#############o####o.#####o#####################o######.######.##o###o#########o.#o##############o#o######o###o######################o
o...ooooooooooooooooooooooooooooo.........ooooooooooooooooooooooooooooooooooo.o.......ooooooooooooooooo....oooooooooooooooooo..ooooo....ooooooo....................o
o#.#o############oo#####o#######o#########o##oo#############################o#o#####.#o###############o#.##o################o##o###o.###o#####o#######.##.#########o
o.oooo.oooooooooooooooooooooooooooo.......oooooooooooooooooooo..oooooooooooooooooooooooooooooooooooooooooooooo........oooooooooo..ooooooooooooooooooooooo..........o
o#o##o#o##############o##o########o#######o##################o##o###############oo#################o#########o####.###o########o##o######o##############o#.#.#####.o
o.ooooooooooo.ooooooooooooooooooooooooooooooooooooo........ooooooo...oooooooooooooooooo............oooooooooooooooooooooooooooooooo.oooooooooooooooooooooooo.......o
o#o#########o#o#################o####oo###########o##.#####o#####o###o################o.##.########o####################o#########o#o##############oo######o###.###o
ooooooooo...oooooooo.......oooooooooooooooooooooooooo.....ooooooooooooo............ooooo..ooooooooooooooo.............oooooooooooooooooooo........ooo.....oooooo...o
o#######o#.#o######o###.###o################o#######o#####o######o####o############o###o##o#############o##########.##o##################o#####.##o#o#####o####o###o
o.......ooooooooooooooooooooo............oooooooooooooooooooooooooooooo.oooooooooooooooooooooooooooooooooo........oooooooo..............oooooooooooooooooooooooooooo
o####.##o###################o.##.########o#########o#o#####o##########o#o################o###########o###o########o######o##.##.###.#.##o#########o####o###########o
o.......o.................ooooooo........oooooooooooooooooooooooo....oooo............ooooooooo......ooooooooooooooooooo..ooooooooooooooooooooooooooo..ooooo........o
o##.####o#######.########.o#####o.#######o############o#########o####o##o##.#########o#######o.#####o#################o#.o#######################o#o##o###o.#######o
o...ooooooooooooo.oooooooooooooooooooooooooo.......oooooooooooooooooooooooooooooooooooooooooooooooooooo..............oooooooooooooooooo.......oooooooooooooooooooo.o
o.##o###########o#o##########o#############o#######o########o##############oo#####################o###o#.##.###.#####o################o.####..o##################o.o
ooooooooo.oooooooooo....ooooooooo........ooooooooooooooooooooooooooo....oooooooooooo.............oooooooooooooo..ooooooooooooooooooooooooooooooo.................o.o
o#######o#o########o.#.#o#######o#.######o##############o##########o.###o##########o##.#.######.#o############o##o############o############o###o###..#########..#o#o
o.......ooooooooooooooooooooooooooooo..oooooo.ooooooooooooo.....oooooooooo.........o.............o............oooooo.........ooooooo...oooooooooo........ooooooooooo
o.####.#o#####o#####################o.#o####o#o###########o#####o########o###.#####o#####.#######o########..##o####o#.#######o#####o##.o####o###o#.###.##o#########o
o......oooooooooooooooooooooooooooooooooooooooooooooooooooo.....ooooooooooooooo....o............ooooooooooooooooooooooooooooooooooooooooooooooooo.....oooooooooooooo
o.#...#o#o######################o######o##################o#####o#############o####o##..########o###############o#########o#####################o#####o############o
o...ooooooooo............oooooooooooooooo.................ooooooooooooooo.oooooooooooooooooooooooooooooooooooooooooooooooooo..................ooooooooooooooo......o
o###o#######o#.#.#######.o##############o######.#########.o#############o#o############o#############oo###########o########o######.##.########o#############o#####.o
o.oooooooooooooooooooooooooo..........ooooooo.........oooooooooo.......oooooooooooooooooooooo...ooooooooooooooooooooo..ooooooooooooooooooooooooooooooooo.ooooooooooo
o#o######o###o#############o#.######.#o#####o#...###..o########o##.#.##o#######o############o###o###############o###o##o############oo#################o#o#########o
o.o....ooooooooo...........o..........o....ooooooooooooooooooooooooooooooooo..ooooo.........o.ooooooo..........oooooooooooooooooooooooooooo............ooooooooooo.o
o#o####o####o##o.##.#.##.##o#.########o.###o#####o######o#######o##########o##o###o#########o.o#####o##########o########oo################o#.##.###.###o#########o#o
o.ooooooooooooooooo.......ooo.ooooooooooooooooooooooooooooooooooooo...ooooooooo.oooooo......oooooooooooooo....ooooooooooooooooooooooo..ooooooooooooooooooooooooooooo
o#o######o####o###o#####.#o#o.o##############oo###################o###o#######o#o####o######o#####o######o####o#oo##################o##o#############o#############o
ooooooooooooooooooo....oooooooooooooooo..ooooooo.......ooooooooooooooooooooooooooooooooooooooo.oooooooooooooo.oooooooo.............oooooooooooooooooooooo..........o
oo################o#.##o##############o.#o#####o#####..o###########o#########o#o###o#########o.o###o########o#o######o#####.###.###o###########o########o####.#####o
oooo.....oooooooooooooooooooooooooooooooooooooooooooooooooo.....oooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ooooooooooooooooooo...o....ooooooo........o
o##o#####o###########################o##o########o########o.####o###################################oo#########o#######o#o#################o###o.###o#####o#######.o
oooooooooooooooooo................ooooooooooooooooo...oooooooooooooooooo...........................oooooooooooooooooooooooo.............oooooooooooooo...oooooo....o
o###o############o#####..###..#.##o###############o###o################o#####.##.###.###.#..##.###.o####o#################o#.#####.#####o#####o####o#o.##o####o###.o
oooooooooooooooooooooo........ooooooo............ooo..o...............ooooooooooo..................ooooooooooooo.........oooo...........oooooooooooooo...o.ooooooooo
o####################o##..####o#####o######..####o#o#.o##.############o#########o###########.######o###########o####.##.#o##o#########.#o############o###o#o#######o
o....................o........o.....o............o.o..o...............o.........o..................o...........o.........o..o...........o............o...o.o.......o
