.................................................................................................................................oooooooooooo...............................
.####.#####..###.###################################################.############.#.#####.######.###########################.#.#.o##########o#####.###################.##.#.
....................................................................................oooooooooooooooooooooooooooooooooooooooooooooooooo....ooooooooooooooooo.................
.#.####..################.###########.##############################################o################################################o####o###############o###.############.
........................................................oooooooooooooooooooooooooooooooo............................oooooooooooooooooooooooooooooooooooooooooooooo..........
.#################.##.#######.##########################o##############################o#######.####################o####################o#######################o.########.
.....ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo............oooooooooooooooo..............ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.....
.####o###########################################################o.###########o##############o###########.##o#############################################o###########o####.
.oooooo..............ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.........ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
.o####o.#############o###########################################################################o#######.#o########################o######################################o
oooooooooooo.....ooooooooooooooooooo.........................................ooooooooooooooooooooooooooooooooo..................oooooooooooooooooooooooo...................o
o##########o#####o#################o########.################################o###############################o################.#o######################o###############.#.#o
o.........ooooooooooooooooooooooooooooooooooooooooooooooooooooo.........oooooooooooooooooo................ooooooooooooooooooooooooooooooo.......oooooooooooooo.............o
o.########o############o######################################o#########o################o#####.##.#######o###################o#########o#######o############o#############o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o##############o################o#######################################o.##o########################o######o##############################o###############################o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.....................o
o############################o#############################################################oo###############o########################################o######.###########.##o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo................................o.....................o
o################################o##################################################################################o#############.######.#######.###o#.##.#####.##########o
o...............ooooooooooooooooooooooooooo...................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...........................ooooooo.................o
o.##############o#########################o###################o########################################################o###############.######.####o#####o############.####o
o.......oooooooooooooooooo............oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o#######o################o#####.######o####o#######################################################################o#o#######################o#############################o
oooooooooooooooooo.oooooooooooooooooooooooooooo............................................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.......................o
o################o#o##############o###########o####################################.#######o#############################o#########################o#######.###############o
ooooooooooooooooooooooooooooooooooooo.........o....................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..o
o###################################o#########o.##.###############.o#########################################o###########################o##############################o##o
o.....ooooooooooooooooooooooooooooooooooooooooooo...oooooooooooooooooooooooooooo.............ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o#####o#########################################o###o##########################o###.#####.###o#####################o#######################################################o
oooooooooooooooooooooooo........................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..................................................o
o######################o########################o#######################################################################o###########.###################.#################.o
o..........oooooooooooooooooooooooooooooooooooooooooooooo........................................................oooooooooooooo............................................o
o.#########o###############################o############o#####################.##################################o############o##############.#######.###########..####.###o
oooooooooooooooooooooo.......ooooooooooooooooooooooooooooooooooooooooooooooo............................ooooooooooooo.........o............................................o
o####################o#######o#####################o#######################o############################o###########o######.##o#########.##################################o
o.................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o#######.#########o##########################################################o#############################################################################################o
ooooooooooooooooooooooooooooooooooooooooooo.........oooooooooooooooooooooooooooooo.........................................................................................o
o#########################################o#########o############################o.############################################################.#####.##########.##########o
o.................................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.........................................................o
o#################################o##################o###########################################################o#######.#####.##.######.#################################o
o............oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..................o
o####.##.####o##########################################################################################################################################o#.################o
oooooooooooooooooooooo....................................................................................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o####################o#####.####.###############################################################.#########o################################################################o
o.................ooooooooooooooooooooooooooooo.............................................ooooooooooooooooooooooooo......................................................o
o#####.#.#########o###########################o#####################################.#######o#######################o######################################################o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.................oooooooooooooo..........................................o
o############################################o###################################################o###############.#o############o#################.########################o
o.................................ooooooooooooooooooooooooooooooo..........................ooooooooooooooooooooooooooooooooooooooo.........................................o
o####.####.####################.##o#############################o#############.#####.######o#############o#######################o########.################################o
o.........oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.......................................o
o#######.#o##############################################o###########################################o################o############o#########.##############.######.#######o
oooooooooooooooooooo...................................oooooooooooooooooooo..................ooooooooooooo...ooooooooooooooooooooooo.......................................o
o##################o##########################.#######.o##################o####.########.####o###########o###o#####################o############.#.############.###########o
o..............ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...........oooooooooooooooooooooooooooooooooooooooooooo....................................o
o##############o######################################o##########o#############o###########o#####o##############o#####################o##.###########################.#####o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo........oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo........................o
o##################################################oo#############o########o####o#############o########o########################o#################o######.#################o
o..................................................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....oooooooooooooooooooooooooooooooooooooooooooooo..o
o######.###.############################.##########o#############################o####################################o####o############################################o##o
o......oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo........................ooooooooooooooooooooooo...........................ooooooooooooooo
o######o##########################################################################o########################o#####################o##.######.#################o#############o
o....oooooooooooooooooo......................................................oooooooooooo..............ooooooooooooooooooooooooooooooooooooooo..............oooooooooooooooo
o####o################o####################.#########################.###.###o##########o##############o#####################################o##############o##############o
oooooooooooooo..ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.................................oooooooooooooooooooooooooooooooo
o############o##o#########################################o########################o######################o#.##############################.o##############################o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..............oooooooooooooooooooooooooooooooo...ooooooooooooooooooooooooooooooooooooooooooooooooooo.........o
o##############o################o############################o###.###.#.####o###########o##################o###o#################################################o####.####o
o..............oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..............oooooooooo..........................ooooooooooooooooooooooooooooooo
o##############o#################################o#####################################o##o##############o########o###############.##########o#############################o
o.......ooooooooo.........................oooooooooooooooooooooooooooo..........oooooooooooo.........ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...o
o#######o#######o#########################o##########################o##########o##########o#########o#################o###############################################o###o
oooooooooooooooooooooooooooooooooo......oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o################################o######o####################o#################o####################################o###o##################################################o
o...............................ooooooooooooooooooooooooooooooooooooooooooooooooooooooo.........................oooooooooooooo.............................................o
o###########################..##o######o##############################################o#######.#################o############o####################################.########o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...........oooooooooooooooo......oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.............o
o###############################################################o###########o##############o######o##########################################################o#############o
o.........ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..........o
o#########o##########################################################################################################################################o##########o#######.##o
o...ooooooooooooooooooooooo..........................................................................................................................ooooooooooooooooooooooo
o###o#####################o##################.#####.##############.##################.#####################.####################################..###o#####################o
o...o..........ooooooooooooooooooooooooooooooooooooooooooo....................................................................................ooooooooooooooo..............o
o#..o#########.o#########################################o####################################.############.####.#####.###.###..##############o#############o##############o
ooooooooooooooooooooooooooooo........................ooooooooooooooo...................................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...........o
oo##########################o..###.##################o#############o#######.#########.#########.#######o#######################################################o##.########o
ooooo..........ooooooooooooooooooooooooooooooooo....ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..............................................o...........o
o###o##########o###############################o####o###########################################################o#############.################################o###..######o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo........................................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o##############o############################################o#####################################.##o######################################################oo#############o
oooooooooooooooooooooooooo.......................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.................................oooooooooooooooooooooooooooooooo
o########################o###############.#######o########################################################o#######.############.############o##############################o
ooooooooooooooooooooooooooooooooooooooooooooooooooooo................................................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o#############################o#####################o###########.############.#######.###############o############################o########################################o
o......................ooooooooooo.........oooooooooooooo..........................................oooooooooooooooooooooooooooooooooooooooooooooooo........................o
o################.#####o#########o########.o############o####################################.#####o##########o###################################o################.#######o
o...............ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..oooooooooooooooo..............o
o###########.###o##########################################################################o##############################################o##o##############o#########.####o
o.............ooooooooo...............................................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....o
o#############o#######o#.#################################.###########o###############################################################################################o.###o
o.ooooooooooooooooooooooooooooooooooo.........................ooooooooooooooooooooooooooooooooooooooooooooooooooo....ooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o#o#################################o#############.###########o#################################################o####o#####################################################o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.oooooooooooooooooooooooooooooooooooooooooooooooo.................................................o
o##################o####################################o###############o#o##############################################o####################.#######.####################o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.......................................o.................................................o
o##############################################################o#################o#######..#########.########.###########o###########.###############.####################.o
o.............................................................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.......................................o
o#####.#################################################.#####o#######o##############################o#############################o#########################.#############o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...............ooooooooooooooooooooo........................o
o##########################################################################################o##################o###.###########o###################o#########.##############o
o.................................................................................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....................o
o#######.############.###############..######################.###############.####o#############################################################o#####o####################o
o............................................................................oooooooooooooooooooooooooooooooooooo..........ooooooooooooooooooooooooooooooooooooooooooooooooo
o##########.##########################.###########.##########################o##################################o##########o###############################################o
o.................................................................oooooooooooooooooooooooooooooooooooooooooooooooooo.....oooooooooooooooooooooooooooooooooooooooooooooooo..o
o############################################.##.#################o##################################o#############o.####o##############################################o##o
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..............................ooooo
o#################################################################################o#####################################################o######.##########.############o##oo
o.....................................................................ooooooooooooooooooooooooooooooooo..............................ooooooooooooooooooooooooooooooooooooooo
o###############.####.################################################o###############################o##############################o###############################o#####o
o...........................................................ooooooooooooooooooooooooooooooooooooooooooooooooooooo.ooooooooooooooooooooooooooooooooooooooooooooooooooooo....o
o#.#################.#######.########.###.##################o###################################################o#o#####################################o#############o###.o
o....................................................ooooooooooooooooooooooo............................oooooooooooooooooooooooooooooo...ooooooooooooooooooooooooooooooooooo
o#########.######.################.#########.##..####o#####################o############################o########o###################o###o#################################o
o....................................................o.....................o............................o........o...................o...o.................................o
