ooooooooooo.......................
o#########o#######.###########.##.
o......ooooo......................
o##.###o###o###################.#.
o..ooooooooooooooo................
o##o#####o#######o######.####.###.
ooooo...ooooo...oooooooooooooo....
o###o#.#o###o###o############o..#.
o.ooooooooooooooooooooo...oooooooo
o#o#######o###########o###o######o
oooo....oooo.........oooooo......o
o##o#.#.o##o#########o####o######o
oooooooooooo..oooooooooooooooo...o
o####o####oo##o##############o###o
oooooooooooooooooooooooooooooooooo
o##########################o#####o
o......................ooooooooo.o
o.#.########.#.########o#######o#o
o....................ooooooooooo.o
o###.########.#.#####o#########o#o
o...................oooooooooooooo
o###########.#.#####o##o#########o
o...............ooooooooooo......o
o#.#.###########o####oo###o######o
o...............o....oo...o......o
