..........ooooooo
.#.#..#.##o#####o
.........ooo....o
.###.##.#o#o#.#.o
.........o.o....o
..#.##.#.o#o.##.o
.........o.o....o
.#.###.#.o#o..##o
.........oooo...o
.###.#...o##o###o
.........o..o...o
.#.##.#..o#.o.##o
........ooooo...o
.#...#..o##oo.#.o
.......ooo.oo...o
.##.###o#o.oo.##o
.......o.o.ooo..o
..#.#..o.o#o#o#.o
.......oooooooo.o
..#...#o##ooo#o#o
....ooooo.ooo.o.o
..#.o###o#ooo.o.o
...oooooooooooo.o
..#o#o#######oo#o
...o.o.......oooo
..#o#o.#####.o#oo
...o.o.......o.oo
