......................................................................................................................................................oooooooooo......................................
.##############..#######..#########.#.#########.##.#...#######.###########...###.##############.#.#..####.############.#.#.#..##.#####.###.###...#####o########o####.##.#.####.###########.##....####.
......................................................................................................................................................o......ooooooooo................................
.##########.#.#.#.#.####.####.##############################.#######.##.#######.####################..#####.##############.##########.#.##.##.###..###o.##.##o#######o####.####..#####.#######.#.####.
......................................................................................................................................................ooooooooo......o................................
.....###.#########.########.#############.#####.#.############..##.#######..#####################.#..######.###.##############.######.#.######.##.####oo######o##.###o#.########.#.#..###.##########..
.....................................................................................................................................................oooooooooooooooooooo.............................
.###.#.####.###.###########.######..#####.###.##########.#..###.##.##########.####.#####.#.############.###.######.######.##########.#######.#####.##o####o#####o#######o##.###################...##..
..............................................................................................................................................ooooooooo...oooooooo......o.............................
.##.#######.##..###########.#########.##.############.#.######...##.####.##.##.#######.###..#######.##..#########.########.##.###.############o#######o###o######o###.##o#####.##.##########.#.#####..
.............................................................................................................................................ooooooo.oooooooooooooooo..ooo............................
.##...##...####.##.##..####.######.####.#.#########.################.#########.##.########..#######.##..######..#.######..#.#.##.####.#...###o#####o#o##############o##o#o.#.#####..#####.##.#.##.###.
.........................................................................................................................................oooooooooooooooooooooooooooooooooooooooo.....................
.####..#####.#.###.#######.#####..#################.###########..#############.##.##.###########.##############.####.#############.######o#####o##################o##o##o#######o##.###.###.####.####.
..............................................................................................................................ooooooooooooooooooo...............ooooooooooo....ooo....................
.####..#.########..############.##.#.###########.###.##..#.#####.########.##.#####.#.##...#.#.##.#.#.#..####...#############.#o###########o#####o###########.###o#####o###o####o#o####.##.#######.###.
..............................................................................................................................o...........o..oooooo............ooooo.oooooooooooooo...................
.###..#.########.########.################.#######..#.########.##.#####.##.##.######.###.#.#..#####.##..#.#########.#########.o#..#.####.#o.#o####o#####.####..o###o.o#o##########o..####.####.##.##..
...........................................................................................................................ooooooo.......ooooooooooooooooooooooooooooooooooooooooooo..................
.....#.#.###.########.####.##.#######..#..#################.#########.####.###.################.##..#######.###..##########o#####o###.##.o##o#############o#####################o##o#################.
.........................................................................................................................oooo...oooooooooooooooooooooo..oooooooooooooooooooooooooooooo................
.###.##.#.###########..#####.####..#.###.##.#####.##.#.###...##################.####.#.####..###.#.##..####..###.#####.#.o##o#.#o########o###########o##o###########oo###############o##############..
...................................................................................................................ooooooooooooooo.......o..........ooooooooo...ooooooo...........ooooo...............
.#######..###.########.###.##########.###.#####.#.##.#.############..########...##.####.######.###.############.###o######o###o##o#.#####o#.########o##o####o###o#####o#.#########o###o####.#####..##.
................................................................................................................ooooooooooooooooooooooooooooooooooooooooooooooooo.....o........ooooooooo..............
..#.###.##.####.#####.#########.############.#####.########.#######.####.##.##.##.######.#######.#.#####.#..#.##o########o###o#o#####o############o##o###o#####oo#####o####.###o#####o#o#.#######.###.
.......................................................................................................oooooooooooooooooooo.ooooooooooooooo..oooooooooooooooooooooooooo.......ooooooooooooooo.........
.##.###########.######.####.#####.##################.##..####.#.################..###############.###.#o#########oo#######o#o#o####o######o##o##########o#####oo######o######.o###oo########o.###.###.
...........................................................................................oooooooooooooo...oooooooooooooooooooooooooo....o..o..........oooooooooooooooooooo.oooooooooo.....o.........
.##.####.#######.##########.####.####..######.#...##########.##..###.##.###########.#######o############o##.o########################o##..o##o.#######.#o##################o#o########o##...o######.#.
...........................................................................................o.........oooooooooooooo............ooooooooooooooooooooooooooooooo.............ooooooooooooooooooo........
..#..##.#####.##.######.#.################.#.######.###...########.######.#####.#########..o.#.####.#o############o.###########o######o######################o####.####.###o###o#######o#####o#.#####.
.........................................................ooooooooooooooooooooooooooooooooooooo.......o.........ooooo..........oooooooooo...................oooooooo.....ooooooooooooooooooooooooo.....
..####...#####..####.###.#####.###.######.####.#.####.###o###################################o.######o##.#####.o###o.##.#.####o#####o##o#############.###.#o######o.#.##o############o####o#####o###..
.....................................................ooooooo............................oooooooooooooooooo....ooooooo........oooo..oooooooo.........ooooooooooo..oooo..ooooooo......ooo...o...oooo....
.######.####.#####.####.############.#.########.#####o#####o#######.###.###.#...########o######o#########o####o#####o.#######o##o##o######o..####.##o#########o#.o##o#.o#####o######o#o###o###o##o##..
....................................................oooooooo....................oooooooooo....ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...
.#######.###.#############...#####..###.##.##.######o######o..#...#####.########o########o####o#######oo#####o###o###########o###o##o#############o####o########o###o###o###########o########o####o#..
............................................oooooooooo...oooooooooooo...........o........o...ooooooooooo....ooooooo........ooooooooooo.........oooooooooo..ooooooooooooooooooo......o........ooooooooo
.##.#..##..##.####.#######.#####.###.####..#o########o...o##########o###########o#....###o###o#########o###.o#####o##.###.#o######o##o#.####.##o######o#o#.o######o##########o#.####o########o#######o
...........................................oooooooooooo..o......oooooo.........ooo.....ooooooooooooooooooooooooooooooooo.ooooooooooooooooooooooooooooooooooooooooooo......ooooo.....oooooooooooo.....o
.###..#.###.#.#.#.###############.#########o##########o##o######o####o####.#.##o#o#####o###o##########o######o#########o.o################o###########o#########o##o###.##o###o#.#..o##########o#####o
........................................ooooooooo..ooooo.o.....ooooooooooooooooooooooooooooo.......ooooooooooooooooooooooooooooooooooooooooo..........o.......ooooooooooooooooooooo.o......oooooo....o
.##.##.####.########.###.###############o#######o##o###o#o#.#.#o##o##########o##o####o####oo#.#####o###########o########o##################o##.#.#####o##.####o###################o.o#..###o####o####o
...................................ooooooooooooooooooooooooooooooooo......oooooooooo.o..oooo....ooooo........ooooooooooooooooooooooooooooooooooooooo.ooo.....ooooo............oooooooooooooooooooo...o
.###.#####.######################.#o#########o#########o###########o######o########o#o##o##o###.o###o.###.###o##oo#########o#######################o.o#o#####o###o#.#.########o############o#####o###o
..................................ooooooo.oooooooooooooooooo.......o.....ooo.....oooooooo..o..oooooooooooo..ooooooooooooooooooooo................ooooooooooooooo.o.....oooooooooooooooo...oooo...o...o
..##########.#####.#####..#.######o#####o#o####o###########o.######o#####o#o#####o######o##o##o##########o##o###oo##############o#.###########.##o#############o#o...#.o##############o#.#o##o##.o###o
................................oooooo.oooo....o.......ooooooooooooooooooooooooooooo.ooooooooooooooo....oooooo..ooooo......ooooooo........ooooooooooooooo......ooooooooooo....oooooooooooooooooooooooo
.##.#.##########.#.##.#.#####.##o####o#o##o####o####.##o#########o######oo##o######o#o#######o#####o####o####o##o###o#####.o#####o######.#o#############o######o####o####o###.o##########o##o#o######o
.............................oooooooooooo.o....o.......o..oooooooooo...oooooooooooooooooooooooo....oooooooooooooooooooo..oooooo.ooo.....ooooooooooo...oooo....oooooooooooooooooooooooooooooooooo.....o
..#.#.####.##.####.####.###..o##########o.o##.#o#######o#.o########o###o#####o########oo######o####o########o###o#####o##o####o#o#o##.##o#########o##.o##o##.#o######################o#########o#.###o
........................oooooooooo.ooooooooooooooooooooooooooooo..ooo..o.....o........ooooooooooooooo.......ooooooooooooooooooooooo....ooooooooooooooooooo.ooooo....................oooooooooooooo...o
.#####.#.##.############o########o#o########oo###oo############o##o#o#.o.#.##o###.##.#o#############o#.####.o#######o##oo#########o####o###o#############o#o###o####.#.#####..######o############o###o
..............ooooooooooooo......o.o........ooooooooooooooo....o..ooooooooooooooooooooooooo.......oooooooooooo.....ooooooooo......o....o...o........oooooooooooooo.................ooooooooooooooooooo
.######.#####.o###########o###.##o#o.#####.#o#############o####o##oo###oo##########o######o#.#####o#####o####o#.##.o###o###o###.##o####o###o##.##..#o########oo##o######.#..#######o###o#############o
...ooooooooooooo........ooooooooooooooo....ooo......ooooooooooooooooo..ooooooo....oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..o.....ooooooooo.............ooooooooooooooo......o
.##o###########o#####.##o#############o##..o#o.#####o########oo##o##o#.o#####o####o##o########o#######o####o###########o##########o#####o########o##o#####o#######o.#.##.#######o#############o..####o
oooooooo...ooooooooooooooooooooooooooooo...o.o.....oooo......ooooooooooooooooooo.oooooo.......o....ooooooooooo.......oooooooooooooooo.ooooo......oooooooooooooooooooooooooo....ooooooooooooooooooooooo
o######o#..o################oo#########o#..o#o#####o##o######o#o##o###o#o######o#o####o#######o.#.#o#########o#.###.#o####o#########o#o###o#####.o########################o#...o#o###################o
o..ooooooooooooo......oooooooo........ooooooooooooooooo....ooooooooooooooo....oooo..ooooooooooooooooo...oooooooooooooooo..o.......ooooooooooooooooo.................oooooooooooooooo.................o
o#.o###########o######o######o#####..#o##o##o#########o#.##o#####oo######o##.#o#oo##o#########o#####o###o#######o######o##o#######o###############o######.#.########o######o#######o##.############.#o
o.ooooooooooooooooooooooooooooo..oooooooooooooooooooooooooooooooooo....oooooooooooooooo.....oooooooooooooooooooooooooo.ooooooooooooooooo...ooooooooooooo.......ooooooooooooooooo.oooo................o
o#o#####o############o####o###o##o############################o###o###.o#####o########o#####o###o#####o##o###########o#o####o##########o###o###########o##..###o######oo#######o#o##o.##.#######.#.#.o
o.oooooooo.ooooooooooooooooooooo.o...........................oooooooo.oooooooooooo....o.....oooooo..ooooooooooooooooooooooooooooooooooooooooo.........oooooo..oooooooooo......oooooooooooo...........o
o#o######o#o#############o#####o#o.######.##.################o###o##o#o##########o####o####.o####o.#o#########o################oo###########o#.##..###o####o#.o#####o##o#.####o##########o..###.....#o
oooooooooooooo........ooooo..ooooo.........................ooooooooooooooo.....oooooo.o..oooooooooooo.......ooooooo........ooooooooooooooooooooo......ooooooooooooooooooooooooo.ooooooooooo..........o
o####o#######o###.####o###o##o##oo.######.#.####..#.######.o#############o####.o####o#o##o##########o##.####o#####o########o##########o########o######o##########o############o#o#########o##.#.#####o
o...ooo.....ooo.......o...o.oooooooooo.....................o..........oooooooooooooooooooooooooooooooo......o.....o.......oooooooooooooooo.....o......o.oooooooooooooooo.ooooooooo......ooooooo......o
o###o#o#####o#o#.#####o.##o#o#o######o.####.###############o##.#.#####o#####o##########o#############o######o###.#o.#.####o#########o####o#####o###..#o#o##############o#o#######o#.###.o#####o######o
oooooooo....ooooooooooooooooooo.....ooooo.................ooooo......oooooooooooo....ooooooooooo..ooooooo..ooooooooooooooooo........o..oooooooooooooooooo......ooooooooooooooooooooo.oooooooooooo....o
o####o#o####o####o###########oo#####o###o..##.########...#o###o.#####o####o#####o#.##o#########o#.o#####o##o###o###o#######o...###.#o##o################o##..#.o###############oo##o#o####o#####o..##o
oooooooooooooooooo...oooooooooooooooooooooooooooooo......oooooooooooooooooooooooooo..o.......oooooooooooooooooooooooooooooooooooooooooooo..........oooooooooooooooooo.........oooooooooooooooooooooooo
o##########o#####o###o############################o######o###o######oo########o###o##o#####.#o###o#######################o#########o####o#..######.o######o#########o.######.#o##############o######oo
o.......ooooooooooooooooooooooo..............ooooooooooooooooooo.oooooooooo.ooooooooooooooooooooooo......................o........oooooooooooo....oooooooooooooooooooooooooooooooo..........oooooooooo
o..#####o##########oo#########o####.#####.###o#######o####oo###o#o########o#o########o############o###..#########.#######o#..#.###o##########o.###o###############oo###o#########o#..#######o########o
o..oooooooooooooooooooooooooooooo..........ooooooooooooo..ooooooooo.....ooooooo......o............o....................oooooooo...o........oooooooooooooooooooooooooooooo.......oooo...ooooooooooooooo
o#.o############oo#########o####o.#####.###o#######o###o##o####o##o#####o#####o##..##o##..#.#.##.#o########.#######.###o######o##.o##.#####o###################o###o####o##..##.o##o.#.o############oo
o.ooooooooooooooooooo.....oooooooo..ooooooooooooo..ooooooooooooooooooooooooooooooooooooooooo.oooooooooooooo.........ooooo.ooooooooooo..ooooooooooo............oooooooo..o...oooooooooooooooo........oo
o#o##########o######o###..o###o##o##o###########o.#o##################o############o#######o#o############o#########o###o#o#########o.#o#########o############o######o.#o###o######o#######o####.#.#oo
oooooooooooooooooooooo....ooooooooooo....oooooooooooooooo............ooo...........o.oooooooooooo.......oooooooooooooooooooooooooooooooo...ooooooooo...ooooooooooooooooooooooooooooooooooooo......oooo
o######o######o######o####o#########o####o########o#####o..#.########o#o##.#####.#.o#o##########o#.####.o#######o#######oo#####o######oo###o#######o###o########oo#####o#o#######oo########o###.##o##o
o..oooooooooooooooooooooooo......ooooooo.ooooooooooooooooooooooooooooooooooooo.ooooooooo...oooooooooooooooooooooooooooooooooooooooooooooooooo..oooooooooooooo...oooo..ooooooooooooo.....oooooooooooooo
o##o####oo#######o#######oo.#.###o#####o.o#########o###########o#############o#o#######o###o########oo##################o#####o####o########o.#o####o#######o##.o##o##o##########oo####.o############o
ooooooooooooooooooo......ooooooooooooooooo.......oooooooo......o...........oooooooo.ooooooooo......oooooooooooooooo..ooooooooooooooo......ooooooo.oooo......ooooooooooooooooooooooooo.ooooooooooooo..o
o####o#######o####o.###.#o###########o###o####.##o######o######o#.#########o##o###o#o####o##o###.##o##############o#.o####oo#######o###.##o##o##o#o##o.#.###o########o##oo##########o.o###########o##o
o....o..ooooooooo.o.....ooo...ooooooooooooooooooooo..oooooooooooo........oooooooooooooo.oooooo.....o.........oooooooooooooooo.....oooooooooooooooooo.o.....ooooo..oooooooooooo....oooooooooooooooooooo
o####o##o#######o#o##.#.o#o.#.o###################o#.o####o#####o########o############o#o##o#o####.o#########o######oo######o.###.o##############o#o#o#####o###o##o##########o####o##o#########o####oo
o.ooooooo...ooooooooooooooooooo.................ooooooo..ooooooooo..oooooooo.......ooooooooooooooooooo..ooooooooooooooooooooooooooooooooo........ooooo.....oooooooooo.....ooooooo.o..o....oooooooooooo
o#o####oo###o######o##########o##.######.###.###o#####o##o#o#####o##o######o######.o#################o#.o#############o#########oo######o########o###o#####o########o##.##o#####o#o##o####o######o###o
oooooooooooooo....ooooooooooooo................oooo...o..oooo...oooooooooooooooooooooooooo...........ooooooooo......oooooo......oooooooooo.....ooooooo...oooooooooooooooooooooooooo..o....o.....ooo..o
o####o####o##o#.##o###########o##.#.####.######o##o###o.#o##o###o#####o##################o####.######o#######o#.####o####o.###.#o#o######o##.#.o#####o###o######o######o######o###o##o####o#.#.#o#o##o
ooooooooooooooooooo.........oooooooooooooooooooooooooooooooooooooo...ooooooooo...........o...........o......oooooooooooooooo...ooooo.....o.....ooooooooooooooooooo....ooooooooooooooooooooo....ooooo.o
o#################o###.###.#o##########o#########o######o########o###o#######o########..#o..##.#.#.#.o####.#o##########oo##o###o###o.####o.####oo############o###o###.o#############o#####o####o###o#o
o...............oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo........ooooo........ooooooooo.oooooooooo..o...oooooooooooooooooo............ooooooooooo............o..ooooooooooooooo
o.######.##...#.o##o#################o####o########o#####oo########oo#o########o######..o###o#.###.##o#######o#o########o#.o##.o##############o#o###.#.#.#..#o#########o##.#########o#.o#############o
o..............ooooooooooooooooo...oooooooooo.....ooooooooo.......ooooooooooooooooooooooooooo....oooooo....ooooooooooooooooooo.o.............oooooooooooooooooo.ooooooooooooooooooooooooooooo........o
o####.####.####o#o#############o##.o####o###o##.#.o#o#####o#######o#########oo#########o####o.#.#o####o###.o###o#############o#o.#.#######.##o####o###########o.o#############o######oo#####o.#####.#o
o............ooooooo...........ooooooooooooooo....oooooo..o..oooooooooooooooooooooo..ooooooooo...o..oooo...ooooooooo........ooooooooooooooooooooooooooooo.ooooooooooo.....ooooooooooooooooooooo......o
o##.#....####o##o##o##.#.######o#########o###o####o####o##o##o#########oo#########o.#o#######o###o#.o##o###oo######o##..###.o##############o####o#######o#o####o####o####.o###################o######o
o.........ooooooooooooooooooooooo..ooooooooooooooooooooooooooooooooooooooo...ooooooooooooooooooooooooooooooooooooooooooooooooo.........oooooooooooooooooooo.oooooooooooooooo..................o......o
o########.o####o#o########o#####o##o#################o#####o##########o##o##.o############o#########oo####o##############o###o#######.#o#############o####o#o####o#########o####.#.##..###.###o.#.##.o
ooooooooooooooooooooooooooooooooooooooooooo.........ooooooooooo.......o..o...o............o.........oooooooooooooooooooooooooooooooo...o............ooooooooooooooo.....ooooooooo......ooooooooo.....o
o##########o###########o#####o###o########o#####.###o##oo#####o.######o##o###o###.########o#####.###oo######################o######o#.#o############o######o####o#o##.##o#######o#.##.#o#######o.###.o
o.........oooooo......oooooooooooo........o.........o..oooooooooo....oooooooooooooo.ooooooooo......ooooo....................o......o.ooooo.........oooooooooooooooooooooooooooooooooooooooooooooo....o
o.###.####o####o######o#o########o########o###.#####o.#o###o####o#.##o############o#o#######o######o###o####################o.#####o.o###o#########o######oo#######o########oo#####o############o#.##o
o.ooooooooooooooooooooooooooooooooo.......o.........o.ooooooooooooooooo......ooooooooo.....oooooooooooooooooooooooooooooooooooo....o.oooooo.....ooooooooooooo.....oooooooooooooooooooooooooooooooo...o
o#o###########o######o#oo#########o.##.###o#######.#o.o###############o##.#.#o#######o##..#o#####oo#########oo################o####o#o####o###.#o#####oo####o##.##o#####o#########o############o#o###o
o.o.........ooooooooooooooooooooo.o...oooooooo......o.o..............ooo...oooooooo..ooooooooooooooooo....oooo................o.oooooooooooooooooooooooooooooooooooooooooo.....ooooooooo.......ooooooo
o#o#########o###################o#o###o######o.#####o.o##############o#o###o######o##o########o######o####o##o###.#########.##o#o#########################o###o########o#o####.o#######o#######o####oo
oooooooooooooo.........oooooooooooo...o....oooooooooooooooo..ooooooooooooooooooooooooooooo....o......oooooooooooooooooo......ooooooooooo.................oooooooooooooooooo..oooooooooooooooooooooo.oo
o############o..#####.#o##########o#.#o#.##o##o###########o##o#########oo#######o##o#####o####o##.##.oo#####o#########o###.#.o#o#######o#.#######.###.##.o#oo##oo#######o#o##o############o#######o#oo
o...ooooooooooooooooooooo...ooooooooooooooooooo..........ooooooooo...ooooooo..ooooooo.ooooooooooo...oooooooooooo......o......ooooooo..ooooooooooooo.....ooooooooooo...oooooooo..........ooooo....ooooo
o###o###################o#.#o##########o######o##.#####.#o#######o###o#####o##o#####o.o####o####o###o######o###o#.####o#.####o#####o.#o###########o..###o#ooo#####o###o######o.########.o###o.###o###o
oooooooo.........ooooooooooooooooo....oooo....o..........o...ooooooooooooooooooo..ooooooooooooooooooooo...ooooooo...ooooooo.oooo...oooooo.......ooooooooooooooooooooooooooooooooo.......oooooooooooooo
o######o#.#.#..##o########o######o####o##o###.o#.########o###o#####o#######oo##o##o#####o#####oo######o###o#####o.##o#####o#o##o#.#o####o#.#####o##o###########o##########o#####o###.###o####o######oo
ooooooooooooooooooo......ooooooooooooooooooooooo..ooooooooooooooooooooooooooo..oooooooooooooooooooooooooooooooooo...o...oooooooooo.o...ooooooo..ooooooo..ooooooooooooooooooooooooo......o....ooooooooo
o#############o###o#.###.o####o################o##o#########################o##o#########o########o#############o###o##.o###oo###o#o#.#o#####o##oo####o.#o#########o#########o###o.####.o####oo######o
o......ooooooooooooooooooooooooooooo...........o..o....................ooooooooo.......ooooooooooooo............o..ooooooooooooooooo..oooo.ooooooooooooooo.........o.......oooooooooooooooooooooooo..o
o.#.###o#####################o#####o###########o##o####.#.#..#####.###.o#######o#######o######o####o#.##########o##o#####o#########o##o##o#o##o###o######o####.###.o####.##o##o#####o######o######o##o
ooooooooooooooo.............oooooo.o..........oooooo..................oooooooooo......ooooooooooooooooooooooooooooooooooooo....ooooooooooooooooooooooooooooo...ooooooo.....ooooooooooooooo.ooooooooooo
o#############o.##.#.#######o####o.o##.#######o#o##o.#####.##########.o#######oo##.###o#########o#########o######o####oo##o####o#######o###o###############o###o#####o.#.##o###o#########o#o########oo
o.............o...........oooooooooooo.ooooooooooooooo..............ooooooooooooooo...o.......ooooooooooooooooooooo..oooooo....oooooooooo..o...............oooooo..oooooooooooooooooooo.ooooooo..ooooo
o..#####.#####o####.####.#o##########o#o#############o.####.####..#.o#############o##.o#.#####o##o################o##o###oo####o########o##o.#.##########.#o####o##o#####o############o#o#####o##o###o
o.....oooooooooooooo..oooooooo.......oooo............o.........ooooooo...........oooo.oooooooooooo...............ooooooooooo.ooooooooooooooooo...........ooooo..o.ooooooooo.........oooooooooooooooooo
o#.###o############o#.o######o#####..o##o##.##.######o.######.#o#####o###########o##o#o##########o#######..##.###o#########o#o##o############o##.#.#...#.o###o..o#o#######o####.##..o##o####o##o#####o
o.....o............ooooooooooo...ooooooooooo....ooooooooooooooooo....o.........ooooooooooooo....ooo............oooooooooooooooooo............o.......oooooooooo.o.o....ooooooooooooooooooooooooooooooo
o#####o.#...##.##.#o#########o###o#########o####o#######oo######o####o#######..o#####o#####o####o#o#.####.##.##o################o.#.#.#######o#######o########o#o.o####o#####o###########o###########o
oooooooooo...oooooooooo....ooooooooooooo...o....oooooooooo....ooooooooo....oooooooooooooooooooooooooooooooooooooo.............oooooooooooooooooooooooooooooooooooooooo.o...ooooo.oooooooooooooo......o
o########o###o########o####o###########o#.#o#..#oo#######o####o###o###o.#.#o#####o##########o#######o###########o##.####.#..##o###################o######o###########o#o###o###o.o############o######o
o......ooooooo.......oooooooo........ooooooooooooooooooooooooooooooo..oooooooooooooooooooooooo....oooooooooooooooo............o...................o.....oooo.........ooooooo..oooo.......ooooooooooooo
o.##..#o#####o.#####.o######o#######.o###o######o##################o#.o############o#########o####o##############o####.###.#.#o.#######.#.######.#o#####o##o####.##.#o#####o#.o##o#######o###########o
o......o....oooooooooooooooooooooo..ooooooooooooooooo......oooooooooooo.......oooooooooooooooooooooo..........ooooooooooooooooooo................oooooooooooo........o....oooooooo.....oooooo........o
o######o###.o############oo######o.#o#o######o######o######o##########o####.##o####################o##.##.####o############o####o.######.#.##.#..o##o#######o###.####o####o######o###.#o####o.#######o
o....ooooooooooooooo....ooooooooooooooooooooooooooooooooooooooooo....oooooooooooo..................o..........o...........ooooooo.............ooooooooooooooooo....oooooooooo..ooooo.oooooooooooooo..o
o####o#############o####o###################o##########o########o#.##o##o#######o.#.####.###.#.#.##o#..###.###o###.#####.#o#####o#.#...####...o############o##o####o###o####o##o###o#o#####o######o##o
ooooooooooooooooooooooooo.................oooo.....oooooo.....ooooooooooooooooooooooooooo.......ooooo.ooooooooooooo..oooooooo..ooooooo......ooooooooooooooooooooooooooooooooo.oooooooooooooo.....ooooo
o###############o#######o.################o##o#####o####o.####o#######oo################o#.#####o###o#o###########o##o######o##o#####o######o##########o###########o########o.o#o##########o###.#o##oo
o.......oooooooooooooooooo.......ooooooooooooo.oooooooooooooooooooooooooo.......ooooooooooooooo.oooooooooooooo.oooooooooooooooooooooooooooooooo.......ooooooooooooooooo...oooooooo.........ooooooooooo
o.##..##o############oo##o###.###o###########o.o################o#######o#.###.#o#############o#o############o#o######o######o################o..##.##o##o############o###o######o.######.#o#########o
ooooooooooooooooo...ooooooooooooooooooooooooooooooo...........ooooo....ooooooooooo......ooooooooo............oooooo.oooooooooooo....oooooooooooooooooooooooo.........ooooooooooooooooo....ooo........o
o###############o###o###o####o################o###o#.#########o###o####o####o####o#.##.#o#######o#.######.###o####o#o##o#######o.##.o######################o#######.#o#o###o#########o##.#o#o.####.##o
o........oooooooooooooooooooooooo......oooooooooooooooo.....oooo..oooooooooooooooooooooooo......o..........ooooooooooooooooooooooooooooooo............oooooooooooooooooooooooooooooooooooooooo.......o
o##.####.o#########o######o#####o...#.#o##############o.##.#o##o#.oo##############o######o######o.######.#.o########oo###########o#######o############o######o########o#o###o#########o####o#o#######o
o........o.........o....oooooooooooooooooooooooooooooooooo..oooooooooooooooooooooooo..oooooooooooooooooo..ooooo....ooo........oooooooooooo........oooooooooooooooooooooooooooooooooooooooooooooooooooo
o#.####.#o#########o.##.o######o###o#########o###########o##oo####o####o###########o#.o################o##o###o.###o#o########o##########o####.###o####################o##oo#########################o
o........o.......ooooooooooooooo...o......oooooooo.......o..oo..oooooooooooooooo.ooooooooooooooooooooooooooooooooooooo........o........ooooooooooooooooo...ooooooooooooooooooooo.....................o
o########o#.#####o#############o#.#o##..##o######o#######o#.oo#.o##############o#o###o################oo##########o##o###..##.o###..###o###o###########o###o###################o###.#####.####.#.####o
o......oooooooooooo............oooooooo...o.....oooo....oooooooooo............ooooooooooo.....oooooooooo.......oooooooo.ooooooooooo...ooooooooooooooooooooooo.............oooooooo...................o
o##.###o######o###o.#######.###o######o###o#####o##o.###o#####o##o#####.##.###o#####o###o###.#o########o#######o######o#o#########o.##o##o########o#########o###..#.#.##.#o######o##.##.#..#########.o
oooooooooooooooooooooooo.......o....oooooooooooooo.o..oooooooooooooooo........o....ooooooooooooooo....oooooooooooooooooooooooooooooooooo.o..oooooooooooooooooo.........ooooooo...o...................o
o###########oo#########o#######o#..#o####o#######o#o##o########o#####o###.###.o#.##o########o####o####o####o#########ooo#########o#oo##o.o##o################o##.....#.o#####o###o###..#..###########o
o...........ooooo.ooooooooooooooooooooooooo......oooooo........o.ooooooooooooooooooo.....oooooooooooooooooooooooooooooooooooo...ooooooooooooo.............oooooo......oooooooooooooo.................o
o.#.#####.##o###o#o##########o##########o#o######o####o####.###o#o##########o######o#####o######o######o#######o############o###o#o####o####o#########.###o####o####.#o############o#######.#######.#o
ooooooooooooooooooooooooooooooooooooooooooooo....o..oooooooooooooooooo..oooooooooooooooooo..oooooooooooooo.ooooooooooooooooooo..o.o....o...ooo............ooooooooooooo..........oooooooooooo........o
o###############o###########o####o##########o#.##o##o##########o#####o##o######o########oo..o######o#####o#o#############o###o##o#o##.#o###o#o######.#.###o###########o#.#######.o##########o.####.##o
o..............ooooooo....ooooooooo.....oooooooooooooooooo...ooooooooooooooooooooooooooooooooooooooooooooooooo.......oooooo..oooooo...ooo.oooooooooooooooooooooooooooooooo....ooooo........ooo.......o
o##.##########.o#####o####o#######o##.##o########o#######o###o#############o############o########oo#o########o#.##.#.o####o.#o####o#.#o#o.o######o##################oo###o##.#o###o.######.o#o#######o
o..........oooooooooooooooooooooooooooooooo...ooooooooooooooooooo......ooooooooo.oooooooooooooooooooooooooooooo......o.oooooooooooooooooooo...ooooo................ooooooooooooooooooooooooooo.......o
o####.#.#..o#######o#####o#####o##########o...o############o####o######o#######o.o########o###############o###o.###.#o#o##########oo######o###o###o#############..#o######################o##o#######o
o........ooooooooooooooooo...ooooooooooooooooooo..........ooooooooooo.oooooooooooo....oooooo...........oooooooo....oooooo.....ooooooooooooo.oooooooooo.........oooooooooooo...............oooooooooo.o
o########o######oo#######o###o###o##########o##o##.###.###o#########o#o#######o##o.###o####o......#####o######o..##o##o#o.####o###########o.o########o#..##.###o##########o...#######.###.o########o#o
o........oooooooooo...oooooo.oooooo........oooooooo.......o.........ooooooo.ooooooooooooo..o......oooooooooooooooooooooooooo..o.....oooooooooo.......oooooooooooo.........o...........oooooooo....oooo
o######.#oo#######o#..o####o.o####o########o######o######.o.####.#.#o#####o#o#######o###o#.o..####o############o###########o##o##..#o######o#o###.###o##########o#########o######..#.#o######o####o##o
o..ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo......o..oooooooo....oooooooooooooooo........oooooo........oooooooooooooooooooooooooooooooooooooooooo....oooooooooooo.oooooooooooooooooo
o##o###############o##########o###########o########o#########o#####.o##o######o#.##o####o#########o##.#####o####o########o#######o########oo##o###############o###o##.#o##########o.o#####oo#########o
oooooooooooooo....ooo.........o.........oooo.......o.......oooooooooooooo.oooooooooooooooooooo..oooooooooooooooooooooo..ooooooooooooooooooooooo...........ooooooooooooooo........ooooooooooo.........o
o############o####o#o.##..#..#o##.#.####o##o.###.##o#####.#o####o#######o#o##################o##o#########oo#########o##o######o#########o####o####.######o########o####o#.###.##o#o###o###o.###.###.o
o........oooooooooooooooooooooooooo...ooooooo.oooooooooooooooooooooooooooooooo.............ooooooooooooo..oo....ooooooooooooooooooo.....ooooooo...........o........oooooooooooo..ooooooooooo.........o
o###..###o#####o##################o###o##o##o#o######oo######o#######o#######o..##########.o###########o##oo#.##o#######o#########o####.o#####o.####.###.#o#####.##o##########o##o#########o#######.#o
o......oooooooooo.........ooooooooooooooooooooooooo..oo.....ooo....ooooooooooooo.........oooo..........ooooooooooooooooooooooooooooooooooooooooooo......ooooo....oooooo...ooooooooooooooo..o.........o
o####.#o########o##.######o################o######o.#oo.###.o#o##.#o####o######o##.####.#o##o.####.####o############o####o#######################o##..##o###o.###o####o.##o#############o.#o##..###.#o
o......o......oooo....ooooooo..............o..oooooooooo...oooooo..o....o..ooooooo..ooooooooo.........ooooooooooooooooo..o....................ooooooooooooooooooooooooo...o.....oooooooooooo.........o
o###..#o##.#.#o##o####o#####o######.###.###o.#o########o###o#o##o.#o##.#o##o#####o##o#######o#########o##o############o.#o###.###.#.#....#..#.o#####o#####o###o#######o###o.####o##########o#.#.#####o
o......o...ooooooooooooooooooooooo....ooooooooooooooooooooooooooooooooooooooooooooooooo.....o.........o.oooo....ooooooooooooo............oooooooooo.ooooooooooooooooooooooooooooo...oooooooooooooooooo
o#.###.o###o######o#######o######o####o#######o##########o###########o#####o##########o####.o###..####o.o##o..##o###########o#..###.##.##o########o.o###########################o###o###############oo
ooooooooooooo.ooooooooooooooooooooooooo......oooooo.ooooooooooo....oooooooooooooooooooooooooooooooooooooooooooooooo.......oooo.......oooooooooo...o.o..........................ooooooooooooooooooooooo
o#######o###o#o######o######o########oo##.###o####o.o#########o###.o###############oo###o###################o#####o#######o##o#####.#o########o###o.o#.##############.#.#######o#####################o
o....oooooooooooooooooooooooooo....ooooooooooooooooooooo......o...oooooo.....ooooooooooooooo...........oooooooooooo......ooooo.......oooooooooooooooo........................ooooooooooo.............o
o###.o#####o#########o########o####o###################o.#.###o###o####o##.##o########oo###o.#######.#.o##########o.###..o##oo###.###oo#############o###.#.######..#.####.###o#########o#######.###.#o
o..oooo.ooooo.......ooooo....ooooooooo......ooooooooooooooooooooooooooooooooooooo....ooooooooooooooooooooooooooooooooooooooooooooo...ooo...........ooooo..................ooooooooo.oooooooooooo.....o
o#.o##o.o###o#..##.#o###o####o#######o#.##.#o############o#######o###oo##o######o####o##o######################o########o########o.##o#o####.#.####o###o#.###.##..#.####.#o#######o#o##########o##.##o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...oooooooooooooooooo.ooooooo....................o.....ooooooo.oooooooooooooo.....ooooooooooo...............o.......o.o........ooooo...o
oo########o#######oo###oo##############o#####################o###oo########o######o#o#####o.##.####.##.#######.o#####o#####o.o####o#######o#...#o#########o#######.#####.#o.######o#o########o###o###o
ooo.......o......oooooooo.............oooooooooooooo.........ooooooooooooooooooooooooooooooooooooooooo....ooooooooooooooo..oooooooooooooooooooooooo......oooooooo.......ooooooooooooooooooooooooooo..o
o#o#.####.o#.###.o######o#..##########o############o###.#####oo#######o#######o##########o###########o#.#.o#######o#####o##o##############o#######o######o######o####.#.o#################o###o###o..o
oooooooooooo.....oooooooooooo.........o..........ooooooooooooooo.ooooooooo....o......ooooooooooo.oooooo.oooooooooooo....oooooooo........ooooooooooooo.ooooooooooooooooo.oooooooooooooooooooooooooooo.o
o##########o####.o##########o#.#####.#o##########o######o######o#o#######o##..o##.###o#########o#o####o#o######o###o####o######o.#######o###o#######o.o###o###########o#oo#################o#######o.o
ooooooooooooo..ooooo.ooooooooooooooooooooo.oooooooooooooooooooooooooooooooo..oooo..ooooo.......oooooooooo......oooooooooooo..oooooo....oooooooooooooooooooo..........ooooooo..............oooooooooo.o
o###########o##o###o.o########oo#########o#o###################o##########o##o##o.#o###o####..#o#####o##o##..##o####o#####o..o####o####o#o#####o##########o.###..##.#o#####o#######.##...#o########o#o
ooooooooooooooooooooooooo..oooooooo.....ooooooo................o.........oooooooooooooooooooooooo....o..oooooooooooooooooooooooooooo..oooooooooooo....oooooooooooooooooooooooooooooooooooooooooooooo.o
oo############o#o#######o#.o######o###.#o#o###o#####.#..#####.#o####..###o#o##o###o#############o####o#.o########o###oo####o####oo#o#.o#####o####o###.o###################o##############o#########o.o
ooooo........ooooooo..ooooooooooooooooooooo.ooooooo........ooooooooooooooooooooooooo...ooooooooooooooooooooooooooooooooo...ooooooooooooooooooooooooooooooo...............oooo........oooooooooooo..o.o
o###o.######.o#####o.#o######o############o#o#####o#####.##o###########o####oo##oo#o###o################o############o#o.##oo####oo###o#######o######o###o#.##.####.#####o##o###.####o##########o.#o.o
o...o.......ooooooooo.o......o.....oooooooooooooooo......oooooo.......oooooooooooooooooooooooo..........o.........ooooooooooooooooooooooooooooooooooooooooooooo......oooooooo.....oooooooooooooooooo.o
o###o#.#.###o#oo####o#o####.#o####.o##############o######o####o######.o#oo###################o######.###o###.##.##o###o##o####o####o###o#########o############o#.##.#o######o####.o######o#########o#o
ooooooooooooooooooooooo.ooooooooooooooooooooooo..ooooo..ooooooooooooooooooooooooo.......ooooooo........oooo.....ooooooooooooo.o...oooooo.........o.........ooooooooooooo..oooooooooooooooooooooooooooo
o#####o###########oo##o#o#####################o.#o###o##o###############o#######o####.##o#####o######..o##o####.o##o########o#o#..o####o#.##.#.##o###.###.#o###########o#.o##oo######################o
o.....o..........ooo..o.o....................oooooooooooooooooo....ooooooooooooooo.....ooooooooo....ooooooooooooooooo......ooooooooooooo...oooooooooo....oooooo.......oooooooooo.....................o
o#..##o###.######o#o#.o#o#########.####.#..##o###o############o.###o###########o#o#####o####o##o####o#############o#o#.###.o#o###o####oo#.#o########o###.o####o####.##o#o###o##o.#.##.#######...#####o
o.....o..........o.o..o.o....................o...o............o....o...........o.o.....o....o..o....o.............o.o......o.o...o....oo...o........o....o....o.......o.o...o..o.....................o
