..................................ooooooooooooo.......................
.##############.#.################o###########o######################.
....................ooooooooooooooooooooooooooooo.....................
.##############.####o###################o#######o#####.#####.#######..
....................o...................o.....oooooooooo..............
.######.############o###.###############o#####o########o#############.
...................oooooooooooo....ooooooooooooooooooooooooooooooooooo
..####.#######.##.#o##########o####o###############o#################o
..............oooooooooooooooooooooooooooooo...oooooo................o
.#############o#################o##########o###o####o###.##.######.##o
........ooooooooooooooooooooooooooooo......oooooooooooo..............o
..######o################o##########o###.##o##########o#.#####.#.####o
oooooooooooooooooooooooooooooooooooooooooo.o.......ooooooooooooooooooo
o###############################o########o#o#####.#o#################o
o...........................ooooooooooooooooooo.ooooooooooo..........o
o#.################.##..##.#o##########o######o#o#########o##########o
o.....................oooooooooooooooooooooooooooooooooooooooo.......o
o##.#######.##########o##########o#############o#############o#######o
oooooooooooooooooooooooooo.....ooooo...........o......ooooooooo......o
o########################o#####o###o.####.#####o######o#######o##.###o
o.................oooooooooooooooooooooooooooooooooooooooooooooooooooo
o#################o###########o#############o########################o
o...........oooooooooooooooooooooooooooooooooooooooooo...............o
o####.######o#################o######################o##############.o
o........ooooooooooooooooooooooooooooooooooo.ooooooooooooooooooooooooo
o########o##################o##############o.o#######################o
o....ooooooooooooooooooooooooooooooooooooooooooooooo.................o
o####o###################o#####o###################o#######.#########o
o....o...............ooooooooooooooooooooooooooooooooooooooooooooooooo
o####o#############.#o########################o######################o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o############################o######################################oo
o...........................ooooooooooooooooooo.............oooooooooo
o##############.###.##.#####o#################o#############o########o
o..........................oooooooooooooooooooooooooooooooooooo......o
o###..###.#################o###########o######################o.#####o
o......................ooooooooooooooooooooooooooooooooooooooooo.....o
o######################o########o##############################o#####o
o...............ooooooooooooooooo........ooooooooooooooooooooooooooooo
o####.###.######o###############o.####.##o###########################o
o....oooooooooooooooooooooooooooooooooooooooooo......................o
o.#.#o###########o############################o###.#######.##.#######o
o.oooooooooooooooooooooo..............ooooooooooooooooooo............o
o#o#############o######o##############o#################o#..#########o
ooooo....ooooooooooooooooooo......oooooooooooooooooooooooo...........o
o###o.###o#################o###.##o####o#################o######.####o
o.oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.....o
o#o####################o###########o##################o########o#####o
oooo............oooooooooooooooooooooooooooooooooooooooooooooooooo...o
o##o########.###o###########o####################################o###o
o.oooooooooooooooooooooooooooooooo........................oooooooooooo
o#o############o##o##############o#######.##.#############o##########o
ooooooooooooooooooooooooooooooooooooooooooooo...oooooooooooooooooo...o
o########o######################o###########o###o################o..#o
o.ooooooooooooooooooooooooooooooooo...ooooooooooo...............oooooo
o#o#########################o#####o.##o#########o######.#######.o####o
oooooooooooooo...........oooooooooooooooo.ooooooooooooo.........o....o
o############o###########o######oo######o#o###########o##.#####.o####o
o..........ooooo....oooooooooooooooooooooooooooooooooooooooooooooooo.o
o##########o###o##.#o##########o###################################o#o
ooooooooooooooooooooooooooooooooo...........oooooooooooooooooooooooooo
o####################o##########o###########o########################o
o....................ooooooooooooooooooooooooo.......................o
o#.#####.#.##########o#######################o###.###########.######.o
o...........oooooooooooo......ooooooooooooooooooooooooooo............o
o..#########o##########o####.#o#########################o#########.##o
o.......oooooooooooooooooooooooooooo....................o............o
o#######o##########################o#######.###.###.####o#######.##..o
ooooooooooooooooooooo.......ooooooooooooooooooooooooooooooooo........o
oo##################o#######o######################o########o########o
oooooo............ooooooooooooooooooooooooooooooo..o....ooooooo......o
o####o############o#############################o##o####o#####o######o
oooooooooooooooooooooooooooooooo.............oooooooooooo.....o......o
o##############################o####.########o##########o#####o######o
o.........ooooooooooooooooooooooo.......oooooooooooooooooooooooooooooo
o.########o#####################o.######o############oo##############o
o.........o................ooooooooooooooooo...oooooooooooooo........o
o########.o#.###.##########o#######o#######o###o############o#######.o
o.......oooooooooooooooooooooo...ooooooooooooooooooooooooooooooooooo.o
o###.###o####################o###o####o#####o######################o#o
oooooooooooooo..oooooooooooooooooooooooooooooooooooooooooooooooooooooo
o############o##o###################o##o#####################o#######o
o............ooooooooooooooooooooooooooooooooo.............ooooooooooo
o.###########o########################o######o#############o#########o
o...........ooooooooooooooooooooooooooooo....o..........ooooo........o
o######.####o#o#########################o####o##########o###o##.####.o
o...oooooooooooooo....................oooooooooooooooooooooooo.......o
o#.#o############o##.###########.#####o######################o.####..o
o..ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o##o##o########################o#################o###################o
o.ooooooooooooooooooo.ooooooooooo........oooooooooooooooooooo........o
o#o#################o#o#########o#####.#.o##################o########o
oooo...............oooo......oooooooooooooooooooo.oooooooooooooooooooo
oo#o###############o##o######o####o#############o#o##################o
ooooooooooooooooooooooo..ooooooooooooooo.......ooooo.................o
o##o#################oo##o#############o#######o###o###############..o
o..o...............ooooooooooooooooooooooooooooooooooooooooooooooooooo
o##o###############o#####################o###########################o
oooooooooooooo....oooooooooooooooooooooooooo.........................o
o############o#.##o###o####################o#####.#.##.####.#########o
o...........ooooooooooooooo............oooooooooooooooooo............o
o#####.#####o#######o#####o############o################o######.#.###o
o........oooooooooooooooooooo..........o..........oooooooooooooooooooo
o.#######o#######o###oo#####o##.#######o#######...o##################o
o..oooooooooooooooooooooooooooo..ooooooooooooooo..o..................o
o##o#######################o##o##o#############o##o..######.#########o
ooooooooooooo......ooooooooooooooooooooooooooooooooooooooooooooooooooo
o###########o##.###o#################################################o
ooooooooooooooooooooooooooooooooooooooo..............................o
o#####################################o####.#####.###########..######o
o...................................oooooooooooooooooo...............o
o######.#.######################.###o################o###############o
o............ooooooooooooooooooooooooooooooooooo.oooooooooooooooo....o
o#######.####o#################################o#o##############o.###o
ooooooooooooooooooooooooooooooooooooooooooooooooooo........ooooooooooo
o######################################o##########o.#######o#########o
o..................................oooooooooooooooooo..ooooooooooo...o
o######.########...################o##########o#####o##o#########o##.o
o............................oooooooooooooooooooooooooooooo...oooooooo
o#.##########..##############o###########o######o#########o###o#####oo
o...........oooooooooooooooooooooooooooooooooooooo.......oooooooo.oooo
o.#########.o######################o#############o#.#####o######o#o##o
o....oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..o
o####o########o########################################o##########o##o
ooooooooooooooooooooo..............................ooooooooooooooooooo
o#####o#############o##..##.#########.#############o#################o
oooooooooooo....oooooooooooooooooo.........ooooooooooooooooooooooooooo
o##########o####o################o###.###.#o#########################o
o.....oooooooooooooooooooooooooooooooooooooo.........................o
o#####o########################oo##########o##.#.########..##########o
ooooooooooooooooo............ooooooooooooooooo.......................o
o###############o##.#########o############o##o#####.##############.##o
ooooooooooooooooooooooooooooooooooo....ooooooooo.....................o
o#################################o####o#######o###########.##..#.###o
o...................oooooooooooooooooooooooooooooooo.................o
o####.#.############o##############################o##.############.#o
o..........ooooooooooooo...........................o.................o
o######.###o###########o.###########.##############o#################o
ooooooooooooo...oooooooooo.................ooooooooooooooooooooooooooo
o###########o.##o########o###.#############o#########################o
o........oooooooo.......oooooooooooooooooooooooooooooooooo...........o
o########o######o#######o#######o########################o###########o
ooooooooooo....oooooooooooooooooo.......................oooooooooooooo
oo########o####o#####o##########o.####.#.####.#######.##o############o
oooooooooooooooooooooooooooooooooooo....................o............o
o###############o##################o######.#############o.#######.##.o
o......oooooooooooooooooooooooooooooooooooo......oooooooooo..........o
o######o##########o#######################o######o########o########.#o
o.oooooooooooooooooooo...............oooooooooooooo....ooooooooooooooo
o#o##################o##.############o############o#.##o############oo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o#####################################oo############o################o
o...................................oooooooooooooooooooooooo.........o
o############.######################o######################o########.o
o................................oooooooooooooooooooooooooooooo......o
o###############.####.###########o#################o##########o######o
o..ooooooooooooooooooooooooooooooooooooooooooooooooo.........ooo.....o
o##o###############################################o#.#######o#o#####o
ooooo...................................oooooooooooooooooooooooooooooo
o###o##.#.########.####.#.#####..#####.#o############################o
ooooooooooooo......................ooooooooooooooooooooooo...........o
o###########o###########.##########o#####################o###########o
o.......ooooooooooo......oooooooooooooooo........oooooooooo..........o
o#####.#o#########o######o##############o#.######o########o.#########o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...o
o#####################o##########################o###############o###o
o..............oooooooooooooooooo................o.........ooooooooooo
o.######.#.####o################o#.##########.###o##.######o#########o
o.............ooooooooooooooooooooooooooooooooooooooooooo.oooo.......o
o#############o#########o################o##############o#o##o.#.##.#o
oooooooooooooooooooooooooooo..oooooooooooooooooooooooooooooooooooooooo
o##########################o#.o###################o##################o
o.......................ooooooooooo.............oooooo...............o
o.##.###################o#########o####.########o####o###.###########o
o.....................oooooooooooooooooooooooooooooooooooooooooooo...o
o##.#############.####o###o###############oo#####o###############o###o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o########################o######o############o####o##################o
o...............ooooooooooooooooooooooooo....o.ooooooo...............o
o###############o#######################o####o#o#####o#############.#o
o......ooooooooooo........oooooooooooooooooooooooooooooo.............o
o######o#########o########o############################o#############o
o...oooooooooo...o....oooooooooooooo.......ooooooooooooooooo.........o
o###o########o###o.###o############o#######o###############o########.o
ooooooooo..oooooooooooooooooooooooooooooooooo..........ooooooooooooooo
o#######o.#o##o#############################o##########o#############o
o..ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.........o
o##o########o##########################o#########o#########o######..#o
oooooo.oooooooooooo..................ooooo.....ooooo.....ooooooooooooo
o####o#o##########o.####.######.#####o###o#####o###o#####o###########o
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o######o########################o##############o######o#############oo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
o###########################o#######o################################o
o.......................ooooooooooooooooooo..........................o
o########.#########.####o######o##########o############.###..########o
o.....................ooooo..ooooooooooooooooooooooooooooooooooo.....o
o###################.#o###o##o###########o#####################o###.#o
ooooooooooooooooooooooooooo..o.ooooooooooooo..................oooooooo
o#########################o#.o#o###########o##.########.######o######o
o.......................ooooooooooooo...ooooooooooooooooooooooooooo..o
o#######################o####o######o.#.o######o##################o##o
o......oooooooooooooooooooooooooooooooooooooooooooo...........oooooo.o
o#.####o##############################o#######o###o###########o####o#o
ooooooooooooooo......................ooooooooooooooooooooooooooooooo.o
o#############o##.#########.#########o##o##########o###############o#o
oooooooooooooooooooooooooooooooooooooooooo.........o..........oooooooo
o###################o####################o#########o##########o######o
ooooooooooooooooooooooo.................ooo.....oooooooooooooooooooo.o
o#####################o.###.###.######.#o#o#####o####o#############o#o
o...ooooooooooooooooooooooooooo........ooooooooooooooooooooooooooooooo
o#.#o#########################o########o##o######################o###o
o..ooooooooo.................oooooooooooooooooo...oooooooooooooooooooo
o#.o#######o#################o########o#oo####o.##o##################o
o..o.......o................oooooooooooooooooooooooooo...............o
o.#o.######o#########.######o############o###########o.####.#########o
oooooooooooo..............oooooooooooooooooooooooooooooooooooooooooooo
oo#########o##############o###################o######################o
oooooooo...o.............ooooooooooooooooooooooo.....................o
o######o#.#o#######.#####o#####################o##########.##.#######o
oooooooooooooooooooooooooooooooooo............oooo...................o
o#######o########################o.###########o##o###############..##o
o.......o........................o............o..o...................o
